/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.Koneksi;
import DAO.AttendanceDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import model.AttendanceModel;
import tableModel.AttendanceTableModel;
import service.AttendanceService;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Locale;
/**
 *
 * @author USer
 */
public class Attendance extends javax.swing.JPanel {

    private final AttendanceService attendanceservice = new AttendanceDAO();
    private final AttendanceTableModel attendancetablemodel = new AttendanceTableModel();
    private Connection conn = new Koneksi().koneksi();
    
    class ComboItem {
    private int id;
    private String name;

    public ComboItem(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return name; // akan muncul di combobox
    }
}

    public Attendance() {
        initComponents();
        
        
         //ADD EMPLOYEENAME COMBO BOX
        employee_dropdown.removeAllItems(); 

        String sql = "SELECT idemployee, employeename FROM employee where isdeleted = 0";

        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("idemployee");
                String name = rs.getString("employeename");
                employee_dropdown.addItem(new view.ComboItem(id, name).toString());
            }
            
            rs.close();
            ps.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        table_attendance.setModel(attendancetablemodel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_dialog = new javax.swing.JDialog();
        add_dialog_panel = new javax.swing.JPanel();
        header_new_departement = new javax.swing.JLabel();
        line_icon = new javax.swing.JLabel();
        employee_label = new javax.swing.JLabel();
        add_on_modal = new javax.swing.JButton();
        cancel_on_modal = new javax.swing.JButton();
        employee_dropdown = new javax.swing.JComboBox<>();
        attendance_label = new javax.swing.JLabel();
        attendance_dropdown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_attendance = new javax.swing.JTable();
        crud_panel = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        header_panel = new javax.swing.JPanel();
        header_name = new javax.swing.JLabel();

        add_dialog.setBackground(new java.awt.Color(255, 255, 255));

        add_dialog_panel.setBackground(new java.awt.Color(255, 255, 255));

        header_new_departement.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        header_new_departement.setText("New Attendance");

        line_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pipe.png"))); // NOI18N

        employee_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employee_label.setText("Employee Name");

        add_on_modal.setText("Add");
        add_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_on_modalActionPerformed(evt);
            }
        });

        cancel_on_modal.setText("Cancel");
        cancel_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_on_modalActionPerformed(evt);
            }
        });

        employee_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        attendance_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        attendance_label.setText("Select Attendance");

        attendance_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN", "OUT" }));
        attendance_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendance_dropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_dialog_panelLayout = new javax.swing.GroupLayout(add_dialog_panel);
        add_dialog_panel.setLayout(add_dialog_panelLayout);
        add_dialog_panelLayout.setHorizontalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(line_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header_new_departement, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addComponent(attendance_label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addComponent(employee_label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_dialog_panelLayout.createSequentialGroup()
                        .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(employee_dropdown, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                .addGap(0, 545, Short.MAX_VALUE)
                                .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, add_dialog_panelLayout.createSequentialGroup()
                                .addComponent(attendance_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))))
        );
        add_dialog_panelLayout.setVerticalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(line_icon)
                    .addComponent(header_new_departement, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(employee_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employee_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(attendance_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(attendance_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout add_dialogLayout = new javax.swing.GroupLayout(add_dialog.getContentPane());
        add_dialog.getContentPane().setLayout(add_dialogLayout);
        add_dialogLayout.setHorizontalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        add_dialogLayout.setVerticalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(400, 600));

        table_attendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_attendance.setPreferredSize(null);
        table_attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_attendanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_attendance);

        crud_panel.setBackground(new java.awt.Color(255, 255, 255));
        crud_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        crud_panel.setForeground(new java.awt.Color(204, 204, 204));

        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/plus.png"))); // NOI18N
        add_button.setText("Add Attendance");
        add_button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonMouseClicked(evt);
            }
        });
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cancel_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_buttonMouseClicked(evt);
            }
        });
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crud_panelLayout = new javax.swing.GroupLayout(crud_panel);
        crud_panel.setLayout(crud_panelLayout);
        crud_panelLayout.setHorizontalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        crud_panelLayout.setVerticalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        header_panel.setBackground(new java.awt.Color(255, 255, 255));

        header_name.setBackground(new java.awt.Color(255, 255, 255));
        header_name.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        header_name.setText("Attendance");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(header_name)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(header_name)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(crud_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(crud_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataTabel() {
//        dataClasses.setVisible(false);
//        addClasses.setVisible(true);

        int row = table_attendance.getSelectedRow();

//        active();
        add_button.setVisible(false);
        cancel_button.setVisible(true);
        add_on_modal.setText("Update");
    }
    
    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here
//        if(add_button.getText().equals("Edit Attendance")) {
//            add_on_modal.setText("Update");
//            dataTabel();
//        } else {
//            add_on_modal.setText("Add");
//        }
        add_dialog.pack();
        add_dialog.setLocationRelativeTo(null);
        add_dialog.setModal(true);
        add_dialog.setVisible(true);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void add_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_on_modalActionPerformed
        // TODO add your handling code here:
        if(add_on_modal.getText().equals("Add")) {
            createData();
        } else {
//            updateData();
        }
    }//GEN-LAST:event_add_on_modalActionPerformed

    private void cancel_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_on_modalActionPerformed
        // TODO add your handling code here:
//        add_dialog.setModal(false);
        add_dialog.dispose();
        loadData();
        resetForm();
    }//GEN-LAST:event_cancel_on_modalActionPerformed

    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add_buttonMouseClicked

    private void cancel_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_buttonMouseClicked

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        loadData();
        resetForm();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void table_attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_attendanceMouseClicked
        // TODO add your handling code here:
//        if(add_button.getText().equals("Add Departement")) {
//            add_button.setText("Edit Departement");
//        }
        add_button.setVisible(false);
        cancel_button.setVisible(true);
    }//GEN-LAST:event_table_attendanceMouseClicked

    private void attendance_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendance_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendance_dropdownActionPerformed

    private void loadData() {
        add_button.setVisible(true);
        cancel_button.setVisible(false);
        List<AttendanceModel> list = attendanceservice.getData();
        attendancetablemodel.setData(list); 

        table_attendance.getColumnModel().getColumn(0).setMinWidth(0);
        table_attendance.getColumnModel().getColumn(0).setMaxWidth(0);
        table_attendance.getColumnModel().getColumn(0).setWidth(0);
    }


   private void createData() {
//        if (validasiInput()) {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("h:mm a", Locale.ENGLISH);
            String getemployeename = (String) employee_dropdown.getSelectedItem();
//            String getattendancetime = attendancetime.getText().trim();
            String getattendancetime = LocalTime.now().format(DateTimeFormatter.ofPattern("hh:mm a", Locale.ENGLISH));
            String getinout = (String) attendance_dropdown.getSelectedItem();
            
            System.out.println("inputTime      = [" + getattendancetime + "]");
            
            System.out.println("Time = [" + getattendancetime + "]");

            String nik = "";
            String outtime = null;
            String intime = null;
            String thresholdtime = null;
            Integer idemployee=0;
            Integer iddept=null;
            Integer islates = 0;
            Integer lateperdays = 0;

            try {
                // Cek duplikasi data
                LocalDate today = LocalDate.now();
                String checkingdoubledata = "SELECT * FROM attendance WHERE isdeleted = 0 AND DATE(created_at) = ? AND employeename = ?";
                PreparedStatement psDouble = conn.prepareStatement(checkingdoubledata);
                psDouble.setDate(1, java.sql.Date.valueOf(today));
                psDouble.setString(2, getemployeename);
                ResultSet rsdouble = psDouble.executeQuery();

                if (rsdouble.next()) {
                    String existingName = rsdouble.getString("employeename");
                    if (
                        existingName.equalsIgnoreCase(getemployeename) &&
                        rsdouble.getString("attendancename").equalsIgnoreCase(getinout)
                    ) {
                        JOptionPane.showMessageDialog(null, "Data absensi untuk " + existingName + " sudah ada hari ini.");
                        rsdouble.close();
                        psDouble.close();
                        return;
                    }
                }

                rsdouble.close();
                psDouble.close();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal memeriksa data absensi ganda.");
                return;
            }

            try {
                // Ambil data karyawan dan threshold
                String getdataemployee = "SELECT idemployee,nik,iddeptemployee FROM employee WHERE isdeleted = 0 AND employeename = ?";
                PreparedStatement dataemployee = conn.prepareStatement(getdataemployee);
                dataemployee.setString(1, getemployeename);
                ResultSet dataemployeers = dataemployee.executeQuery();

                if (dataemployeers.next()) {
                    idemployee = dataemployeers.getInt("idemployee");
                    nik = dataemployeers.getString("nik");
                    iddept = dataemployeers.getInt("iddeptemployee");

                    String getthreshold = "SELECT * FROM threshold WHERE iddeptthreshold = ? AND attendancename = ? AND isdeleted = 0";
                    PreparedStatement datathreshold = conn.prepareStatement(getthreshold);
                    datathreshold.setInt(1, iddept);
                    datathreshold.setString(2, getinout);
                    ResultSet datathresholdforatt = datathreshold.executeQuery();

                    if (datathresholdforatt.next()) {
                        LocalTime inputTime = LocalTime.parse(getattendancetime, formatter);
                        System.out.println("inputTime      = [" + getattendancetime + "]");
                        
                        if (datathresholdforatt.getString("attendancename").equalsIgnoreCase("OUT")) {
                            outtime = datathresholdforatt.getString("endtimestr");
                            
                            System.out.println("outtime        = [" + outtime + "]");

                            LocalTime endTime = LocalTime.parse(outtime, formatter);

                            if (inputTime.isBefore(endTime)) {
                                JOptionPane.showMessageDialog(null, "Absensi keluar tidak boleh lebih dulu dibanding threshold (" + outtime + ")");
                                return;
                            }

                        } else if (datathresholdforatt.getString("attendancename").equalsIgnoreCase("IN")) {
                            outtime = datathresholdforatt.getString("endtimestr").toUpperCase().replaceAll("(?<=\\d)(AM|PM)$", " $1");
                            thresholdtime = datathresholdforatt.getString("thresholdtimestr").toUpperCase().replaceAll("(?<=\\d)(AM|PM)$", " $1");
                            
                            System.out.println("outtime       = [" + outtime + "]");
System.out.println("thresholdtime = [" + thresholdtime + "]");
System.out.println("formatter     = " + formatter);

                            LocalTime endTime = LocalTime.parse(outtime, formatter);
                            LocalTime thresholdTime = LocalTime.parse(thresholdtime, formatter);

                            if (inputTime.isAfter(endTime) && inputTime.isBefore(thresholdTime)) {
                                islates = 1;
                                lateperdays = (int) Duration.between(endTime, inputTime).toMinutes();
                            } else if (inputTime.isAfter(thresholdTime)) {
                                JOptionPane.showMessageDialog(null, "Anda dianggap tidak masuk karena melebihi waktu threshold.");
                                return;
                            } else if (inputTime.isBefore(endTime) || inputTime.equals(endTime)) {
                                islates = 0;
                                lateperdays = 0;
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Threshold untuk karyawan yang dipilih tidak ditemukan");
                        return;
                    }

                    datathresholdforatt.close();
                }

                dataemployeers.close();

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal memeriksa data kehadiran.");
                return;
            }

            // Simpan ke database atau model Anda di sini jika diperlukan
            AttendanceModel attendancemodel = new AttendanceModel();
            attendancemodel.setIdEmployee(idemployee);
            attendancemodel.setNikEmployee(nik);
            attendancemodel.setEmployeeName(getemployeename);
            attendancemodel.setAttendanceName(getinout);
            attendancemodel.setAttendanceTime(getattendancetime);
            attendancemodel.setIsLate(islates);
            attendancemodel.setLatePerDays(lateperdays);

            attendanceservice.addAttendance(attendancemodel);
            attendancetablemodel.addAttendance(attendancemodel);

            loadData();
            resetForm();
            add_dialog.dispose();
//            showPanel();
            add_on_modal.setText("Add");
//        }
    }

    private void resetForm() {
//        btnTambah.requestFocus();
        add_on_modal.setText("Add");
        employee_dropdown.setSelectedIndex(0);
        attendance_dropdown.setSelectedIndex(0);
//        txtNotes.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JDialog add_dialog;
    private javax.swing.JPanel add_dialog_panel;
    private javax.swing.JButton add_on_modal;
    private javax.swing.JComboBox<String> attendance_dropdown;
    private javax.swing.JLabel attendance_label;
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton cancel_on_modal;
    private javax.swing.JPanel crud_panel;
    private javax.swing.JComboBox<String> employee_dropdown;
    private javax.swing.JLabel employee_label;
    private javax.swing.JLabel header_name;
    private javax.swing.JLabel header_new_departement;
    private javax.swing.JPanel header_panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel line_icon;
    private javax.swing.JTable table_attendance;
    // End of variables declaration//GEN-END:variables
}
