/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.Koneksi;
import dao.AttendanceLimitDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import model.AttendanceLimitModel;
import tableModel.AttendanceLimitTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.*;
import service.AttendanceLimitService;
import java.sql.SQLException;
import java.sql.*;
import config.Koneksi;
import java.sql.ResultSet;
/**
 *
 * @author USer
 */

class ComboItemAttendanceLimit {
    private int id;
    private String name;

    public ComboItemAttendanceLimit(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return name; // akan muncul di combobox
    }
}

public class AttendanceLimit extends javax.swing.JPanel {

    private AttendanceLimitService attendancelimitservice = new AttendanceLimitDAO();
    private AttendanceLimitTableModel attendancelimittablemodel = new AttendanceLimitTableModel();
    private Connection conn = new Koneksi().koneksi();

    public AttendanceLimit() {
        initComponents();
        
        //ADD DEPARTEMENT & LEVEL COMBO BOX
        departement_dropdown.removeAllItems(); 

        String sql = "SELECT iddept, deptname FROM departement where isdeleted = 0";

        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                int id = rs.getInt("iddept");
                String name = rs.getString("deptname");
                departement_dropdown.addItem(new ComboItemAttendanceLimit(id, name).toString());
            }
            
            rs.close();
            ps.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }

        table_attendance_limit.setModel(attendancelimittablemodel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_dialog = new javax.swing.JDialog();
        add_dialog_panel = new javax.swing.JPanel();
        header_new_attendance_limit = new javax.swing.JLabel();
        line_icon = new javax.swing.JLabel();
        departement_label = new javax.swing.JLabel();
        add_on_modal = new javax.swing.JButton();
        cancel_on_modal = new javax.swing.JButton();
        departement_dropdown = new javax.swing.JComboBox<>();
        attendance_dropdown = new javax.swing.JComboBox<>();
        attendance_label = new javax.swing.JLabel();
        batas_tepat_waktu_field = new com.github.lgooddatepicker.components.TimePicker();
        waktu_mulai_absensi_field = new com.github.lgooddatepicker.components.TimePicker();
        waktu_akhir_jam_absensi_field = new com.github.lgooddatepicker.components.TimePicker();
        waktu_mulai_absensi_label = new javax.swing.JLabel();
        batas_tepat_waktu_label = new javax.swing.JLabel();
        waktu_akhir_jam_absensi_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_attendance_limit = new javax.swing.JTable();
        crud_panel = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        header_panel = new javax.swing.JPanel();
        header_name = new javax.swing.JLabel();

        add_dialog.setBackground(new java.awt.Color(255, 255, 255));

        add_dialog_panel.setBackground(new java.awt.Color(255, 255, 255));

        header_new_attendance_limit.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        header_new_attendance_limit.setText("New Attendance Limit");

        line_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pipe.png"))); // NOI18N

        departement_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departement_label.setText("Departement");

        add_on_modal.setText("Add");
        add_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_on_modalActionPerformed(evt);
            }
        });

        cancel_on_modal.setText("Cancel");
        cancel_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_on_modalActionPerformed(evt);
            }
        });

        departement_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        attendance_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN", "OUT" }));
        attendance_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendance_dropdownActionPerformed(evt);
            }
        });

        attendance_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        attendance_label.setText("Attendance");

        waktu_mulai_absensi_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        waktu_mulai_absensi_label.setText("Waktu Mulai Absensi");

        batas_tepat_waktu_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        batas_tepat_waktu_label.setText("Batas Tepat Waktu");

        waktu_akhir_jam_absensi_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        waktu_akhir_jam_absensi_label.setText("Waktu Akhir Jam Absensi");

        javax.swing.GroupLayout add_dialog_panelLayout = new javax.swing.GroupLayout(add_dialog_panel);
        add_dialog_panel.setLayout(add_dialog_panelLayout);
        add_dialog_panelLayout.setHorizontalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(line_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(header_new_attendance_limit, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departement_label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(departement_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attendance_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attendance_label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(waktu_mulai_absensi_field, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(waktu_mulai_absensi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(batas_tepat_waktu_field, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(batas_tepat_waktu_label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(waktu_akhir_jam_absensi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(waktu_akhir_jam_absensi_field, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        add_dialog_panelLayout.setVerticalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(line_icon)
                    .addComponent(header_new_attendance_limit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addComponent(departement_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departement_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addComponent(attendance_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attendance_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waktu_mulai_absensi_label)
                    .addComponent(batas_tepat_waktu_label)
                    .addComponent(waktu_akhir_jam_absensi_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waktu_mulai_absensi_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batas_tepat_waktu_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waktu_akhir_jam_absensi_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout add_dialogLayout = new javax.swing.GroupLayout(add_dialog.getContentPane());
        add_dialog.getContentPane().setLayout(add_dialogLayout);
        add_dialogLayout.setHorizontalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        add_dialogLayout.setVerticalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(400, 600));

        table_attendance_limit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_attendance_limit.setPreferredSize(null);
        table_attendance_limit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_attendance_limitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_attendance_limit);

        crud_panel.setBackground(new java.awt.Color(255, 255, 255));
        crud_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        crud_panel.setForeground(new java.awt.Color(204, 204, 204));

        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/plus.png"))); // NOI18N
        add_button.setText("Add Attendance Limit");
        add_button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonMouseClicked(evt);
            }
        });
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete (1).png"))); // NOI18N
        delete_button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        delete_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_buttonMouseClicked(evt);
            }
        });
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cancel_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_buttonMouseClicked(evt);
            }
        });
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crud_panelLayout = new javax.swing.GroupLayout(crud_panel);
        crud_panel.setLayout(crud_panelLayout);
        crud_panelLayout.setHorizontalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crud_panelLayout.setVerticalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        header_panel.setBackground(new java.awt.Color(255, 255, 255));

        header_name.setBackground(new java.awt.Color(255, 255, 255));
        header_name.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        header_name.setText("Attendance Limit");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(header_name)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(header_name)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(crud_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(crud_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

       private void dataTabel() {
//        dataUser.setVisible(false);
//        addUser.setVisible(true);

        int row = table_attendance_limit.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select.");
            return;
        }

//        jLabel2.setText("Perbarui Data Karyawan");
        header_new_attendance_limit.setText("Edit Attendance Limit");

        int thresholdid = (int) table_attendance_limit.getModel().getValueAt(row, 0);
        AttendanceLimitModel thresholdmodel = attendancelimitservice.getById(thresholdid);

        if (thresholdmodel == null) {
            JOptionPane.showMessageDialog(null, "Attendance limit data not found.");
            return;
        }
        
        String getiddept = "SELECT deptname FROM departement WHERE iddept=? AND isdeleted=0";
        
         try {
            PreparedStatement psiddept = conn.prepareStatement(getiddept);
            psiddept.setInt(1, thresholdmodel.getIdDept());
            ResultSet rsIdDept = psiddept.executeQuery();

            String deptname = null;
            if (rsIdDept.next()) {
                deptname = rsIdDept.getString("deptname");
                
                // Set nilai ke input form
                waktu_mulai_absensi_field.setText(thresholdmodel.getStarttimestr());
                attendance_dropdown.setSelectedItem(thresholdmodel.getAttendancename());
                batas_tepat_waktu_field.setText(thresholdmodel.getEndtime());
                waktu_akhir_jam_absensi_field.setText(thresholdmodel.getAttendanceLimittime());
                departement_dropdown.setSelectedItem(deptname);
                
            } else {
                JOptionPane.showMessageDialog(null, "Departement not found!");
                return;
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, 
                "Failed to proccess data departemenr:\n" + e.getMessage());
        }

//        active();
        add_on_modal.setText("Update");
        cancel_button.setVisible(true);
    }
       
    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here
        if(add_button.getText().equals("Edit Attendance Limit")) {
            add_on_modal.setText("Update");
            dataTabel();
        } else {
            add_on_modal.setText("Add");
        }
        add_dialog.pack();
        add_dialog.setLocationRelativeTo(null);
        add_dialog.setModal(true);
        add_dialog.setVisible(true);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void add_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_on_modalActionPerformed
        // TODO add your handling code here:
        if(add_on_modal.getText().equals("Add")) {
            createData();
        } else {
            updateData();
        }
    }//GEN-LAST:event_add_on_modalActionPerformed

    private void cancel_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_on_modalActionPerformed
        // TODO add your handling code here:
//        add_dialog.setModal(false);
        add_dialog.dispose();
        loadData();
        resetForm();
    }//GEN-LAST:event_cancel_on_modalActionPerformed

    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add_buttonMouseClicked

    private void delete_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_buttonMouseClicked

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void cancel_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_buttonMouseClicked

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        loadData();
        resetForm();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void table_attendance_limitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_attendance_limitMouseClicked
        // TODO add your handling code here:
        if(add_button.getText().equals("Add Attendance Limit")) {
            add_button.setText("Edit Attendance Limit");
        }
        delete_button.setVisible(true);
        cancel_button.setVisible(true);
    }//GEN-LAST:event_table_attendance_limitMouseClicked

    private void attendance_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendance_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendance_dropdownActionPerformed

     private void loadData() {
        delete_button.setVisible(false);
        cancel_button.setVisible(false);
        List<AttendanceLimitModel> list = attendancelimitservice.getData();
        attendancelimittablemodel.setData(list);

        table_attendance_limit.getColumnModel().getColumn(0).setMinWidth(0);
        table_attendance_limit.getColumnModel().getColumn(0).setMaxWidth(0);
        table_attendance_limit.getColumnModel().getColumn(0).setWidth(0);
    }

    private void createData() {
        String getstarttime = waktu_mulai_absensi_field.getText();
        String getendtime = batas_tepat_waktu_field.getText();
        String getthreshold = waktu_akhir_jam_absensi_field.getText();
        String getdepartemen = departement_dropdown.getSelectedItem().toString();
        String getattendancename = attendance_dropdown.getSelectedItem().toString();
        String getiddept = "SELECT iddept FROM departement WHERE deptname=? AND isdeleted=0";
         String checkdata = "SELECT iddeptthreshold FROM threshold WHERE iddeptthreshold=? AND attendancename=? AND isdeleted=0";
        try {
            PreparedStatement psiddept = conn.prepareStatement(getiddept);
            psiddept.setString(1, getdepartemen);
            ResultSet rsIdDept = psiddept.executeQuery();
            
            Integer iddept = null;
            if (rsIdDept.next()) {
                iddept = rsIdDept.getInt("iddept");
                 PreparedStatement checkdataid = conn.prepareStatement(checkdata);
                 checkdataid.setInt(1, iddept);
                 checkdataid.setString(2, getattendancename);
                 ResultSet rsCheckData = checkdataid.executeQuery();
                 if(rsCheckData.next()){
                    JOptionPane.showMessageDialog(null, "Attendance limit for departement "+getdepartemen+" already registered");
                    return; 
                 }
            } else {
                JOptionPane.showMessageDialog(null, "Departement not found!");
                return;
            }

            AttendanceLimitModel thresholdmodel = new AttendanceLimitModel();
            thresholdmodel.setAttendancename(getattendancename);
            thresholdmodel.setIdDept(iddept);
            thresholdmodel.setStarttimestr(getstarttime);
            thresholdmodel.setEndtime(getendtime);
            thresholdmodel.setAttendanceLimittime(getthreshold);

            attendancelimitservice.addAttendanceLimit(thresholdmodel);
            attendancelimittablemodel.addAttendanceLimit(thresholdmodel);

            loadData();
            add_dialog.dispose();
            resetForm();
//            showPanel();
            add_on_modal.setText("Add");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, 
                "Failed to proccess attendance limit:\n" + e.getMessage());
        }
    }


    private void updateData() {
        int row = table_attendance_limit.getSelectedRow();
        if (row != -1) {
            int thresholdid = (int) table_attendance_limit.getModel().getValueAt(row, 0);
            String getiddept = "SELECT iddept FROM departement WHERE deptname=? AND isdeleted=0";
            String checkdata = "SELECT iddeptthreshold,idthreshold FROM threshold WHERE iddeptthreshold=? AND attendancename=? AND isdeleted=0";
            String getstarttime = waktu_mulai_absensi_field.getText();
            String getendtime = batas_tepat_waktu_field.getText();
            String getthreshold = waktu_akhir_jam_absensi_field.getText();
            String getattendancename = attendance_dropdown.getSelectedItem().toString();
            String getdepartemen = departement_dropdown.getSelectedItem().toString();

            try {
                PreparedStatement psiddept = conn.prepareStatement(getiddept);
                psiddept.setString(1, getdepartemen);
                ResultSet rsIdDept = psiddept.executeQuery();

                Integer iddept = null;
                if (rsIdDept.next()) {
                    iddept = rsIdDept.getInt("iddept");
                     PreparedStatement checkdataid = conn.prepareStatement(checkdata);
                     checkdataid.setInt(1, iddept);
                     checkdataid.setString(2, getattendancename);
                     ResultSet rsCheckData = checkdataid.executeQuery();
                     if(rsCheckData.next()){
                         if(rsCheckData.getInt("idthreshold")!= thresholdid){
                            JOptionPane.showMessageDialog(null, "Attendance limit for departement "+getdepartemen+" already registered");
                            return; 
                         }
                     }
                } else {
                    JOptionPane.showMessageDialog(null, "Departement not found!");
                    return;
                }

                AttendanceLimitModel thresholdmodel = new AttendanceLimitModel();
                thresholdmodel.setId(thresholdid);
                thresholdmodel.setIdDept(iddept);
                thresholdmodel.setAttendancename(getattendancename);
                thresholdmodel.setStarttimestr(getstarttime);
                thresholdmodel.setEndtime(getendtime);
                thresholdmodel.setAttendanceLimittime(getthreshold);

                attendancelimitservice.editAttendanceLimit(thresholdmodel);
                attendancelimittablemodel.editAttendanceLimit(row, thresholdmodel);

                loadData();
                resetForm();
                add_dialog.dispose();
//                showPanel();

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                    "Failed to proccess attendance limit:\n" + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select!");
        }
    }

    private void deleteData() {
        int index = table_attendance_limit.getSelectedRow();
        if (index != -1) {
            int thresholdid = (int) table_attendance_limit.getModel().getValueAt(index, 0);
            AttendanceLimitModel getAttendanceLimit = attendancelimitservice.getById(thresholdid);

            AttendanceLimitModel thresholdmodel = getAttendanceLimit;

            if (JOptionPane.showConfirmDialog(null, "Are you sure, you want delete this data?", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                attendancelimitservice.deleteAttendanceLimit(thresholdmodel);
                attendancelimittablemodel.deleteAttendanceLimit(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select");
        }
    }

    private void resetForm() {
//        btnTambah.requestFocus();
        add_button.setText("Add Attendance Limit");
        header_new_attendance_limit.setText("New Attendance Limit");
        waktu_mulai_absensi_field.setText("");
        attendance_dropdown.setSelectedIndex(0);
        departement_dropdown.setSelectedIndex(0);
        batas_tepat_waktu_field.setText("");
        waktu_akhir_jam_absensi_field.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JDialog add_dialog;
    private javax.swing.JPanel add_dialog_panel;
    private javax.swing.JButton add_on_modal;
    private javax.swing.JComboBox<String> attendance_dropdown;
    private javax.swing.JLabel attendance_label;
    private com.github.lgooddatepicker.components.TimePicker batas_tepat_waktu_field;
    private javax.swing.JLabel batas_tepat_waktu_label;
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton cancel_on_modal;
    private javax.swing.JPanel crud_panel;
    private javax.swing.JButton delete_button;
    private javax.swing.JComboBox<String> departement_dropdown;
    private javax.swing.JLabel departement_label;
    private javax.swing.JLabel header_name;
    private javax.swing.JLabel header_new_attendance_limit;
    private javax.swing.JPanel header_panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel line_icon;
    private javax.swing.JTable table_attendance_limit;
    private com.github.lgooddatepicker.components.TimePicker waktu_akhir_jam_absensi_field;
    private javax.swing.JLabel waktu_akhir_jam_absensi_label;
    private com.github.lgooddatepicker.components.TimePicker waktu_mulai_absensi_field;
    private javax.swing.JLabel waktu_mulai_absensi_label;
    // End of variables declaration//GEN-END:variables
}
