/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.Koneksi;
import dao.DepartemenDAO;
import java.sql.Connection;
import javax.swing.Popup;
import service.DeptService;
import tableModel.DeptTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import model.DeptModel;


/**
 *
 * @author USer
 */

public class Departement extends javax.swing.JPanel {

    /**
     * Creates new departement
     */
    
    private DeptService departementService = new DepartemenDAO();
    private DeptTableModel departementTableModel = new DeptTableModel();
    private Connection conn = Koneksi.koneksi();
    
    public Departement() {
        initComponents();
        
        table_departement.setModel(departementTableModel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_dialog = new javax.swing.JDialog();
        add_dialog_panel = new javax.swing.JPanel();
        header_new_departement = new javax.swing.JLabel();
        line_icon = new javax.swing.JLabel();
        departement_fields = new javax.swing.JTextField();
        departement_label = new javax.swing.JLabel();
        add_on_modal = new javax.swing.JButton();
        cancel_on_modal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_departement = new javax.swing.JTable();
        crud_panel = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        header_panel = new javax.swing.JPanel();
        header_name = new javax.swing.JLabel();

        add_dialog.setBackground(new java.awt.Color(255, 255, 255));

        add_dialog_panel.setBackground(new java.awt.Color(255, 255, 255));

        header_new_departement.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        header_new_departement.setText("New Departement");

        line_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pipe.png"))); // NOI18N

        departement_fields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departement_fieldsActionPerformed(evt);
            }
        });

        departement_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departement_label.setText("Departement Name");

        add_on_modal.setText("Add");
        add_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_on_modalActionPerformed(evt);
            }
        });

        cancel_on_modal.setText("Cancel");
        cancel_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_on_modalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_dialog_panelLayout = new javax.swing.GroupLayout(add_dialog_panel);
        add_dialog_panel.setLayout(add_dialog_panelLayout);
        add_dialog_panelLayout.setHorizontalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(line_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header_new_departement, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addComponent(departement_label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(departement_fields)
                            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                .addGap(0, 543, Short.MAX_VALUE)
                                .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );
        add_dialog_panelLayout.setVerticalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(line_icon)
                    .addComponent(header_new_departement, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(departement_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departement_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout add_dialogLayout = new javax.swing.GroupLayout(add_dialog.getContentPane());
        add_dialog.getContentPane().setLayout(add_dialogLayout);
        add_dialogLayout.setHorizontalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        add_dialogLayout.setVerticalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(400, 600));

        table_departement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_departement.setPreferredSize(null);
        table_departement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_departementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_departement);

        crud_panel.setBackground(new java.awt.Color(255, 255, 255));
        crud_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        crud_panel.setForeground(new java.awt.Color(204, 204, 204));

        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/plus.png"))); // NOI18N
        add_button.setText("Add Departement");
        add_button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonMouseClicked(evt);
            }
        });
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete (1).png"))); // NOI18N
        delete_button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        delete_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_buttonMouseClicked(evt);
            }
        });
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cancel_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_buttonMouseClicked(evt);
            }
        });
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crud_panelLayout = new javax.swing.GroupLayout(crud_panel);
        crud_panel.setLayout(crud_panelLayout);
        crud_panelLayout.setHorizontalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crud_panelLayout.setVerticalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        header_panel.setBackground(new java.awt.Color(255, 255, 255));

        header_name.setBackground(new java.awt.Color(255, 255, 255));
        header_name.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        header_name.setText("Departement");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(header_name)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(header_name)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(crud_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(crud_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataTabel() {
        
        int row = table_departement.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu.");
            return;
        }

        header_new_departement.setText("Edit Departement");

        // Ambil ID user dari tabel
        int levelId = (int) table_departement.getModel().getValueAt(row, 0);
        DeptModel departementModel = departementService.getById(levelId);
        departement_fields.setText(departementModel.getDeptName());

        // Aktifkan input form
//        active();
//        add_on_modal.setText("Perbarui");
        cancel_on_modal.setVisible(true);
    }
    
    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here
        if(add_button.getText().equals("Edit Departement")) {
            add_on_modal.setText("Update");
            dataTabel();
        } else {
            add_on_modal.setText("Add");
        }
        add_dialog.pack();
        add_dialog.setLocationRelativeTo(null);
        add_dialog.setModal(true);
        add_dialog.setVisible(true);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void departement_fieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departement_fieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departement_fieldsActionPerformed

    private void add_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_on_modalActionPerformed
        // TODO add your handling code here:
        if(add_on_modal.getText().equals("Add")) {
            createData();
        } else {
            updateData();
        }
    }//GEN-LAST:event_add_on_modalActionPerformed

    private void cancel_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_on_modalActionPerformed
        // TODO add your handling code here:
//        add_dialog.setModal(false);
        add_dialog.dispose();
        loadData();
        resetForm();
    }//GEN-LAST:event_cancel_on_modalActionPerformed

    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add_buttonMouseClicked

    private void delete_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_buttonMouseClicked

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void cancel_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_buttonMouseClicked

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        loadData();
        resetForm();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void table_departementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_departementMouseClicked
        // TODO add your handling code here:
        if(add_button.getText().equals("Add Departement")) {
            add_button.setText("Edit Departement");
        }
        delete_button.setVisible(true);
        cancel_button.setVisible(true);
    }//GEN-LAST:event_table_departementMouseClicked

    private void loadData() {
        delete_button.setVisible(false);
        cancel_button.setVisible(false);
        add_button.setText("Add Departement");
        List<DeptModel> list = departementService.getData();
        System.out.println("LIST" + list);
        departementTableModel.setData(list);
        departementTableModel.fireTableDataChanged();

        table_departement.getColumnModel().getColumn(0).setMinWidth(0);
        table_departement.getColumnModel().getColumn(0).setMaxWidth(0);
        table_departement.getColumnModel().getColumn(0).setWidth(0);
    }
    
    private void createData() {
        if(validasiInput()) {
            String position = departement_fields.getText();
                  
                DeptModel departementModel = new DeptModel();
                departementModel.setDeptName(position);
                
                departementService.addDept(departementModel);
                departementTableModel.addDept(departementModel);
                
                loadData();
                add_dialog.dispose();
                resetForm();
           } 
        }
    
     private void updateData() {
        int row = table_departement.getSelectedRow();
        if (row != -1) {
            if (validasiInput() == true) {
                String deptname = departement_fields.getText();

                DeptModel deptmodel = new DeptModel();
                deptmodel.setId((int) table_departement.getModel().getValueAt(row, 0));
                deptmodel.setDeptName(deptname);

                departementService.editDept(deptmodel);
                departementTableModel.editDept(row, deptmodel);
                loadData();
                resetForm();
                add_dialog.dispose();
//                showPanel();
            }
        }
    }
    
    private void deleteData() {
        int index = table_departement.getSelectedRow();
        if (index != -1) {
            int deptId = (int) table_departement.getModel().getValueAt(index, 0);
            DeptModel getDept = departementService.getById(deptId);

            DeptModel deptmodel = getDept;

            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                departementService.deleteDept(deptmodel);
                departementTableModel.deleteDept(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }
    

    
    private boolean validasiInput() {
        boolean valid = false;
        if(departement_fields.getText().isEmpty() || departement_fields.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Departement Name cannot be null!");
        } else {
            valid = true;
        }
        
        return valid;
    }
    
    private void resetForm() {
        departement_fields.setText("");
        header_new_departement.setText("Add Departement");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JDialog add_dialog;
    private javax.swing.JPanel add_dialog_panel;
    private javax.swing.JButton add_on_modal;
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton cancel_on_modal;
    private javax.swing.JPanel crud_panel;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField departement_fields;
    private javax.swing.JLabel departement_label;
    private javax.swing.JLabel header_name;
    private javax.swing.JLabel header_new_departement;
    private javax.swing.JPanel header_panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel line_icon;
    private javax.swing.JTable table_departement;
    // End of variables declaration//GEN-END:variables
}
