/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.Koneksi;
import dao.EmployeeSalaryDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import model.EmployeeSalaryModel;
import tableModel.EmployeeSalaryTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import service.EmployeeSalaryService;
import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.sql.SQLException;


/**
 *
 * @author wayan
 */

public class EmployeeSalaryPerMonth extends javax.swing.JPanel {

    private EmployeeSalaryService employeesalaryservice = new EmployeeSalaryDAO();
    private EmployeeSalaryTableModel employeesalarytablemodel = new EmployeeSalaryTableModel();
    private Connection conn = new Koneksi().koneksi();

    public EmployeeSalaryPerMonth() {
        initComponents();
        tblBasicSalary.setModel(employeesalarytablemodel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBasicSalary = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        addUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatalTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dategenerate = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(899, 620));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataUser.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblBasicSalary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBasicSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBasicSalaryMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblBasicSalaryMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblBasicSalary);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Data Gaji Karyawan");

        btnTambah.setText("Tambah");
        btnTambah.setPreferredSize(new java.awt.Dimension(85, 30));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setPreferredSize(new java.awt.Dimension(85, 30));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.setPreferredSize(new java.awt.Dimension(85, 30));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataUserLayout = new javax.swing.GroupLayout(dataUser);
        dataUser.setLayout(dataUserLayout);
        dataUserLayout.setHorizontalGroup(
            dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(dataUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataUserLayout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataUserLayout.setVerticalGroup(
            dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataUser, "card2");

        addUser.setBackground(new java.awt.Color(255, 255, 255));
        addUser.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setText("Tambah Data Karyawan");
        addUser.add(jLabel2);
        jLabel2.setBounds(6, 6, 887, 36);

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setText("Tambah");
        btnSimpan.setPreferredSize(new java.awt.Dimension(74, 30));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        addUser.add(btnSimpan);
        btnSimpan.setBounds(708, 73, 85, 30);

        btnBatalTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBatalTambah.setText("Batal");
        btnBatalTambah.setPreferredSize(new java.awt.Dimension(85, 30));
        btnBatalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTambahActionPerformed(evt);
            }
        });
        addUser.add(btnBatalTambah);
        btnBatalTambah.setBounds(811, 73, 85, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Bulan Gaji Karyawan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dategenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(426, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(dategenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(746, Short.MAX_VALUE))
        );

        addUser.add(jPanel1);
        jPanel1.setBounds(0, 121, 902, 830);

        mainPanel.add(addUser, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void dataTabel() {
        dataUser.setVisible(false);
        addUser.setVisible(true);

        int row = tblBasicSalary.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu.");
            return;
        }

        jLabel2.setText("Perbarui Data Gaji Bulanan");

        int userId = (int) tblBasicSalary.getModel().getValueAt(row, 0);
        EmployeeSalaryModel employeesalarymodel = employeesalaryservice.getById(userId);

        if (employeesalarymodel == null) {
            JOptionPane.showMessageDialog(null, "Data user tidak ditemukan.");
            return;
        }


        active();
        btnSimpan.setText("Perbarui");
        btnSimpan.setVisible(false);
        btnBatalTambah.setVisible(true);
    }


    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(addUser);
        mainPanel.repaint();
        mainPanel.revalidate();

        btnSimpan.setText("Simpan");
        if (btnTambah.getText().equals("Ubah")) {
            dataTabel();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBatalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTambahActionPerformed
        showPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btnBatalTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        switch (btnSimpan.getText()) {
            case "Tambah" ->
                btnSimpan.setText("Simpan");
            case "Simpan" ->
                createData();
            default -> {
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblBasicSalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBasicSalaryMouseClicked
        if (btnTambah.getText().equals("Tambah")) {
            btnTambah.setText("Ubah");
        }

        btnHapus.setVisible(true);
        btnTambah.setVisible(false);
        btnBatal.setVisible(true);
    }//GEN-LAST:event_tblBasicSalaryMouseClicked

    private void tblBasicSalaryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBasicSalaryMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBasicSalaryMousePressed

    private void active() {
        dategenerate.setEnabled(true);
    }

    private void loadData() {
        btnHapus.setVisible(false);
        btnBatal.setVisible(false);
        List<EmployeeSalaryModel> list = employeesalaryservice.getData();
        employeesalarytablemodel.setData(list);

        tblBasicSalary.getColumnModel().getColumn(0).setMinWidth(0);
        tblBasicSalary.getColumnModel().getColumn(0).setMaxWidth(0);
        tblBasicSalary.getColumnModel().getColumn(0).setWidth(0);
    }

    private void createData() {
        Date selectedDate = dategenerate.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(null, "Tanggal belum dipilih!");
            return;
        }

        Calendar cal = Calendar.getInstance();
        cal.setTime(selectedDate);
        int month = cal.get(Calendar.MONTH) + 1;
        int year = cal.get(Calendar.YEAR);

        String checksql = "SELECT COUNT(*) FROM salarypermonth WHERE MONTH(created_at)=? AND YEAR(created_at)=? AND isdeleted=0";
        String updatesql = "UPDATE salarypermonth SET isdeleted = 1 WHERE MONTH(created_at)=? AND YEAR(created_at)=? AND isdeleted = 0";

        // Tanpa alias
        String basicsalaryQuery = "SELECT basicsalary.basicsalary, employee.idemployee, employee.nik " +
                                  "FROM basicsalary INNER JOIN employee ON basicsalary.idemployeebasicsalary = employee.idemployee " +
                                  "WHERE basicsalary.isdeleted = 0";

        String attendancedata = "SELECT SUM(totallateperdays) AS totalLate FROM vw_attendance " +
                                "WHERE MONTH(attendancedate)=? AND YEAR(attendancedate)=? AND idemployee=? GROUP BY employeename";

        String overtimedata = "SELECT SUM(duration) AS totalOvertime FROM overtime " +
                              "WHERE isdeleted = 0 AND MONTH(created_at)=? AND YEAR(created_at)=? AND idemployeeovertime=? GROUP BY idemployeeovertime";

        try {
            // Step 1: Cek apakah data sudah ada
            PreparedStatement psCheck = conn.prepareStatement(checksql);
            psCheck.setInt(1, month);
            psCheck.setInt(2, year);
            ResultSet rsCheck = psCheck.executeQuery();

            if (rsCheck.next() && rsCheck.getInt(1) > 0) {
                // Step 2: Update isdeleted jika data sudah ada
                PreparedStatement psUpdate = conn.prepareStatement(updatesql);
                psUpdate.setInt(1, month);
                psUpdate.setInt(2, year);
                psUpdate.executeUpdate();
            }

            // Step 3: Insert data baru dari tabel basicsalary dan employee
            PreparedStatement psSalary = conn.prepareStatement(basicsalaryQuery);
            ResultSet rsSalary = psSalary.executeQuery();

            while (rsSalary.next()) {
                int idemployee = rsSalary.getInt("idemployee");
                String nik = rsSalary.getString("nik");
//                String employeename = rsSalary.getString("employeename");
//                String levelname = rsSalary.getString("levelname");
//                String deptname = rsSalary.getString("deptname");
                int basicsalary = rsSalary.getInt("basicsalary");

                // Hitung potongan keterlambatan
                PreparedStatement psLate = conn.prepareStatement(attendancedata);
                psLate.setInt(1, month);
                psLate.setInt(2, year);
                psLate.setInt(3, idemployee);
                ResultSet rsLate = psLate.executeQuery();
                int cutlate = 0;
                if (rsLate.next()) {
                    cutlate = rsLate.getInt("totalLate") * 5000;
                }

                // Hitung bonus lembur
                PreparedStatement psOvertime = conn.prepareStatement(overtimedata);
                psOvertime.setInt(1, month);
                psOvertime.setInt(2, year);
                psOvertime.setInt(3, idemployee);
                ResultSet rsOvertime = psOvertime.executeQuery();
                int overtimebonus = 0;
                if (rsOvertime.next()) {
                    overtimebonus = rsOvertime.getInt("totalOvertime") * 5000;
                }

                // Hitung total gaji bulan ini
                int totalsalarythismonth = basicsalary + overtimebonus - cutlate;

                // Simpan ke model
                EmployeeSalaryModel employeesalarymodel = new EmployeeSalaryModel();
                employeesalarymodel.setIdEmployee(idemployee);
                employeesalarymodel.setEmployeeNik(nik);
                employeesalarymodel.setBasicSalary(basicsalary);
                employeesalarymodel.setOvertimeBonus(overtimebonus);
                employeesalarymodel.setCutLate(cutlate);
                employeesalarymodel.setSalaryThisMonth(totalsalarythismonth);

                // Tambahkan ke service dan tabel
                employeesalaryservice.addEmployeeSalary(employeesalarymodel);
                employeesalarytablemodel.addEmployeeSalary(employeesalarymodel);
            }

            // Refresh UI dan tampilkan pesan
            loadData();
            resetForm();
            showPanel();
            btnSimpan.setText("Tambah");
            JOptionPane.showMessageDialog(null, "Data gaji berhasil diproses.");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memproses data gaji:\n" + e.getMessage());
        }
    }


    private void deleteData() {
        int index = tblBasicSalary.getSelectedRow();
        if (index != -1) {
            int employeesalaryid = (int) tblBasicSalary.getModel().getValueAt(index, 0);
            EmployeeSalaryModel getemployeesalary = employeesalaryservice.getById(employeesalaryid);

            EmployeeSalaryModel employeesalarymodel = getemployeesalary;

            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                employeesalaryservice.deleteEmployeeSalary(employeesalarymodel);
                employeesalarytablemodel.deleteEmployeeSalary(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }


    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new EmployeeSalaryPerMonth());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void resetForm() {
        btnTambah.requestFocus();
        btnTambah.setText("Tambah");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addUser;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatalTambah;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel dataUser;
    private com.toedter.calendar.JDateChooser dategenerate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tblBasicSalary;
    // End of variables declaration//GEN-END:variables
}
