/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.Koneksi;
import dao.EmployeeSalaryDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import model.EmployeeSalaryModel;
import tableModel.EmployeeSalaryTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import service.EmployeeSalaryService;
import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;


/**
 *
 * @author USer
 */

public class EmployeeSalaryPerMonth extends javax.swing.JPanel {

    private EmployeeSalaryService employeesalaryservice = new EmployeeSalaryDAO();
    private EmployeeSalaryTableModel employeesalarytablemodel = new EmployeeSalaryTableModel();
    private Connection conn = new Koneksi().koneksi();

    public EmployeeSalaryPerMonth() {
        initComponents();
        table__monthly_salary.setModel(employeesalarytablemodel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_dialog = new javax.swing.JDialog();
        add_dialog_panel = new javax.swing.JPanel();
        header_new_monthly_salary = new javax.swing.JLabel();
        line_icon = new javax.swing.JLabel();
        monthly_salary_label = new javax.swing.JLabel();
        add_on_modal = new javax.swing.JButton();
        cancel_on_modal = new javax.swing.JButton();
        dategenerate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        table__monthly_salary = new javax.swing.JTable();
        crud_panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        header_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        add_dialog.setBackground(new java.awt.Color(255, 255, 255));

        add_dialog_panel.setBackground(new java.awt.Color(255, 255, 255));

        header_new_monthly_salary.setText("New Monthly Salary");
        header_new_monthly_salary.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N

        line_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pipe.png"))); // NOI18N

        monthly_salary_label.setText("Monthly Employees Salary");
        monthly_salary_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        add_on_modal.setText("Add");
        add_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_on_modalActionPerformed(evt);
            }
        });

        cancel_on_modal.setText("Cancel");
        cancel_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_on_modalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_dialog_panelLayout = new javax.swing.GroupLayout(add_dialog_panel);
        add_dialog_panel.setLayout(add_dialog_panelLayout);
        add_dialog_panelLayout.setHorizontalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(line_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header_new_monthly_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addComponent(monthly_salary_label, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dategenerate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 543, Short.MAX_VALUE)
                                .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );
        add_dialog_panelLayout.setVerticalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(header_new_monthly_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line_icon))
                .addGap(24, 24, 24)
                .addComponent(monthly_salary_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dategenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout add_dialogLayout = new javax.swing.GroupLayout(add_dialog.getContentPane());
        add_dialog.getContentPane().setLayout(add_dialogLayout);
        add_dialogLayout.setHorizontalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        add_dialogLayout.setVerticalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(400, 600));

        table__monthly_salary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table__monthly_salary.setPreferredSize(null);
        table__monthly_salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table__monthly_salaryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table__monthly_salary);

        crud_panel.setBackground(new java.awt.Color(255, 255, 255));
        crud_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        crud_panel.setForeground(new java.awt.Color(204, 204, 204));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/plus.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete (1).png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crud_panelLayout = new javax.swing.GroupLayout(crud_panel);
        crud_panel.setLayout(crud_panelLayout);
        crud_panelLayout.setHorizontalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crud_panelLayout.setVerticalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        header_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Monthly Employees Salary");
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(crud_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(crud_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataTabel() {
//        dataUser.setVisible(false);
//        addUser.setVisible(true);

        jButton1.setVisible(false);

        int row = table__monthly_salary.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu.");
            return;
        }

//        header_new_monthly_salary.setText("Edit Monthly Salary");

        int userId = (int) table__monthly_salary.getModel().getValueAt(row, 0);
        EmployeeSalaryModel employeesalarymodel = employeesalaryservice.getById(userId);

        if (employeesalarymodel == null) {
            JOptionPane.showMessageDialog(null, "Data user tidak ditemukan.");
            return;
        }


//        active();
//        add_on_modal.setText("Perbarui");
        add_on_modal.setVisible(false);
//        btnBatalTambah.setVisible(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        add_dialog.pack();
        add_dialog.setLocationRelativeTo(null);
        add_dialog.setModal(true);
        add_dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_on_modalActionPerformed
        // TODO add your handling code here:
        createData();
    }//GEN-LAST:event_add_on_modalActionPerformed

    private void cancel_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_on_modalActionPerformed
        // TODO add your handling code here:
//        add_dialog.setModal(false);
        add_dialog.dispose();
        resetForm();
    }//GEN-LAST:event_cancel_on_modalActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
//        if (jButton1.getText().equals("Edit Employee")) {
//            dataTabel();
//        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void table__monthly_salaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table__monthly_salaryMouseClicked
        // TODO add your handling code here:
        jButton1.setVisible(false);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    }//GEN-LAST:event_table__monthly_salaryMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        loadData();
        resetForm();
    }//GEN-LAST:event_jButton3ActionPerformed

private void loadData() {
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton1.setVisible(true);
        List<EmployeeSalaryModel> list = employeesalaryservice.getData();
        employeesalarytablemodel.setData(list);

        table__monthly_salary.getColumnModel().getColumn(0).setMinWidth(0);
        table__monthly_salary.getColumnModel().getColumn(0).setMaxWidth(0);
        table__monthly_salary.getColumnModel().getColumn(0).setWidth(0);
    }

    private void createData() {
        Date selectedDate = dategenerate.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(
                null,
                "Silakan pilih periode gaji terlebih dahulu!"
            );
            return;
        }
        LocalDate salaryPeriod = selectedDate
        .toInstant()
        .atZone(ZoneId.systemDefault())
        .toLocalDate();
        
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(null, "Please select date!");
            return;
        }

        Calendar cal = Calendar.getInstance();
        cal.setTime(selectedDate);
        int month = cal.get(Calendar.MONTH) + 1;
        int year = cal.get(Calendar.YEAR);

        String checksql = "SELECT COUNT(*) FROM salarypermonth WHERE MONTH(salary_period)=? AND YEAR(salary_period)=? AND isdeleted=0";
        String updatesql = "UPDATE salarypermonth SET isdeleted = 1 WHERE MONTH(salary_period)=? AND YEAR(salary_period)=? AND isdeleted = 0";

        // Tanpa alias
        String basicsalaryQuery = "SELECT basicsalary.basicsalary, employee.idemployee, employee.nik " +
                                  "FROM basicsalary INNER JOIN employee ON basicsalary.idemployeebasicsalary = employee.idemployee " +
                                  "WHERE basicsalary.isdeleted = 0";

        String attendancedata = "SELECT SUM(totallateperdays) AS totalLate FROM vw_attendance " +
                                "WHERE MONTH(attendancedate)=? AND YEAR(attendancedate)=? AND idemployee=? GROUP BY employeename";

        String overtimedata = "SELECT SUM(duration) AS totalOvertime FROM overtime " +
                              "WHERE isdeleted = 0 AND MONTH(created_at)=? AND YEAR(created_at)=? AND idemployeeovertime=? GROUP BY idemployeeovertime";

        try {
            // Step 1: Cek apakah data sudah ada
            PreparedStatement psCheck = conn.prepareStatement(checksql);
            psCheck.setInt(1, month);
            psCheck.setInt(2, year);
            ResultSet rsCheck = psCheck.executeQuery();

            if (rsCheck.next() && rsCheck.getInt(1) > 0) {
                // Step 2: Update isdeleted jika data sudah ada
                PreparedStatement psUpdate = conn.prepareStatement(updatesql);
                psUpdate.setInt(1, month);
                psUpdate.setInt(2, year);
                psUpdate.executeUpdate();
            }

            // Step 3: Insert data baru dari tabel basicsalary dan employee
            PreparedStatement psSalary = conn.prepareStatement(basicsalaryQuery);
            ResultSet rsSalary = psSalary.executeQuery();

            while (rsSalary.next()) {
                int idemployee = rsSalary.getInt("idemployee");
                String nik = rsSalary.getString("nik");
//                String employeename = rsSalary.getString("employeename");
//                String levelname = rsSalary.getString("levelname");
//                String deptname = rsSalary.getString("deptname");
                int basicsalary = rsSalary.getInt("basicsalary");

                // Hitung potongan keterlambatan
                PreparedStatement psLate = conn.prepareStatement(attendancedata);
                psLate.setInt(1, month);
                psLate.setInt(2, year);
                psLate.setInt(3, idemployee);
                ResultSet rsLate = psLate.executeQuery();
                int cutlate = 0;
                if (rsLate.next()) {
                    cutlate = rsLate.getInt("totalLate") / 60 * 20000;
                }

                // Hitung bonus lembur
                PreparedStatement psOvertime = conn.prepareStatement(overtimedata);
                psOvertime.setInt(1, month);
                psOvertime.setInt(2, year);
                psOvertime.setInt(3, idemployee);
                ResultSet rsOvertime = psOvertime.executeQuery();
                int overtimebonus = 0;
                if (rsOvertime.next()) {
                    overtimebonus = rsOvertime.getInt("totalOvertime") / 60 * 50000;
                }

                // Hitung total gaji bulan ini
                int totalsalarythismonth = basicsalary + overtimebonus - cutlate;

                // Simpan ke model
                EmployeeSalaryModel employeesalarymodel = new EmployeeSalaryModel();
                employeesalarymodel.setIdEmployee(idemployee);
                employeesalarymodel.setEmployeeNik(nik);
                employeesalarymodel.setBasicSalary(basicsalary);
                employeesalarymodel.setOvertimeBonus(overtimebonus);
                employeesalarymodel.setCutLate(cutlate);
                employeesalarymodel.setSalaryThisMonth(totalsalarythismonth);
                employeesalarymodel.setSalaryPeriod(salaryPeriod);

                // Tambahkan ke service dan tabel
                employeesalaryservice.addEmployeeSalary(employeesalarymodel);
                employeesalarytablemodel.addEmployeeSalary(employeesalarymodel);
            }

            // Refresh UI dan tampilkan pesan
            loadData();
            resetForm();
//            showPanel();
            add_dialog.dispose();
            JOptionPane.showMessageDialog(null, "Success proccess salary data.");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Failed proccess salary:\n" + e.getMessage());
        }
    }


    private void deleteData() {
        int index = table__monthly_salary.getSelectedRow();
        if (index != -1) {
            int employeesalaryid = (int) table__monthly_salary.getModel().getValueAt(index, 0);
            EmployeeSalaryModel getemployeesalary = employeesalaryservice.getById(employeesalaryid);

            EmployeeSalaryModel employeesalarymodel = getemployeesalary;

            if (JOptionPane.showConfirmDialog(null, "Are you sure, you want delete this data?", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                employeesalaryservice.deleteEmployeeSalary(employeesalarymodel);
                employeesalarytablemodel.deleteEmployeeSalary(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select");
        }
    }

    private void resetForm() {
//        btnTambah.requestFocus();
        dategenerate.setDate(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog add_dialog;
    private javax.swing.JPanel add_dialog_panel;
    private javax.swing.JButton add_on_modal;
    private javax.swing.JButton cancel_on_modal;
    private javax.swing.JPanel crud_panel;
    private com.toedter.calendar.JDateChooser dategenerate;
    private javax.swing.JLabel header_new_monthly_salary;
    private javax.swing.JPanel header_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel line_icon;
    private javax.swing.JLabel monthly_salary_label;
    private javax.swing.JTable table__monthly_salary;
    // End of variables declaration//GEN-END:variables
}
