/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.Koneksi;
import dao.EmployeeDAO;
import java.sql.Connection;
import javax.swing.Popup;
import service.EmployeeService;
import tableModel.EmployeeTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import model.EmployeeModel;


/**
 *
 * @author USer
 */

class ComboItemDept {
    private int id;
    private String name;

    public ComboItemDept(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return name; // akan muncul di combobox
    }
}

class ComboItemLevel {
    private int id;
    private String name;

    public ComboItemLevel(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return name; // akan muncul di combobox
    }
}

public class Employee extends javax.swing.JPanel {

    /**
     * Creates new form Employee
     */
    
    private EmployeeService userService = new EmployeeDAO();
    private EmployeeTableModel userTableModel = new EmployeeTableModel();
    private Connection conn = Koneksi.koneksi();
    
    public Employee() {
        initComponents();

        departement_dropdown.removeAllItems();
        level_dropdown.removeAllItems();
        
        String sqlDept = "select iddept, deptname from departement where isdeleted = 0";
        String sqlLevel = "select idlevel, levelname from level where isdeleted = 0";
        
        
        
        try {
            PreparedStatement stDept = conn.prepareStatement(sqlDept);
            ResultSet rsDept = stDept.executeQuery();
            
            PreparedStatement stLevel = conn.prepareStatement(sqlLevel);
            ResultSet rsLevel = stLevel.executeQuery();
            
            while (rsDept.next()) {
                int idDept = rsDept.getInt("iddept");
                String nameDept = rsDept.getString("deptname");
                departement_dropdown.addItem(new ComboItemDept(idDept, nameDept).toString());
            }
            
            while (rsLevel.next()) {
                int idLevel = rsLevel.getInt("idlevel");
                String nameLevel = rsLevel.getString("levelname");
                level_dropdown.addItem(new ComboItemLevel(idLevel, nameLevel).toString());
            }
            
            stDept.close();
            rsDept.close();
            stLevel.close();
            rsLevel.close();
        } catch (Exception e) {
            e.printStackTrace();
        } 
        
        table_user.setModel(userTableModel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_dialog = new javax.swing.JDialog();
        add_dialog_panel = new javax.swing.JPanel();
        header_new_employee = new javax.swing.JLabel();
        line_icon = new javax.swing.JLabel();
        employee_name_fields = new javax.swing.JTextField();
        nik_fields = new javax.swing.JTextField();
        nik_label = new javax.swing.JLabel();
        employee_name_label = new javax.swing.JLabel();
        departement_dropdown = new javax.swing.JComboBox<>();
        level_dropdown = new javax.swing.JComboBox<>();
        level_label = new javax.swing.JLabel();
        departement_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        no_telp_fields = new javax.swing.JTextField();
        no_telp_label = new javax.swing.JLabel();
        alamat_fields = new javax.swing.JTextField();
        alamat_label = new javax.swing.JLabel();
        add_on_modal = new javax.swing.JButton();
        cancel_on_modal = new javax.swing.JButton();
        password_fields = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        crud_panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        header_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        add_dialog.setBackground(new java.awt.Color(255, 255, 255));

        add_dialog_panel.setBackground(new java.awt.Color(255, 255, 255));

        header_new_employee.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        header_new_employee.setText("New Employee");

        line_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pipe.png"))); // NOI18N

        nik_fields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nik_fieldsActionPerformed(evt);
            }
        });

        nik_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nik_label.setText("NIK");

        employee_name_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employee_name_label.setText("Employee Name");

        departement_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        departement_dropdown.setMinimumSize(new java.awt.Dimension(64, 22));
        departement_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departement_dropdownActionPerformed(evt);
            }
        });

        level_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        level_dropdown.setPreferredSize(new java.awt.Dimension(64, 22));
        level_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level_dropdownActionPerformed(evt);
            }
        });

        level_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        level_label.setText("Level");

        departement_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departement_label.setText("Departement");

        password_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password_label.setText("Password");

        no_telp_fields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_telp_fieldsActionPerformed(evt);
            }
        });

        no_telp_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        no_telp_label.setText("Nomor Telepon");

        alamat_fields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat_fieldsActionPerformed(evt);
            }
        });

        alamat_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alamat_label.setText("Alamat");

        add_on_modal.setText("Add");
        add_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_on_modalActionPerformed(evt);
            }
        });

        cancel_on_modal.setText("Cancel");
        cancel_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_on_modalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_dialog_panelLayout = new javax.swing.GroupLayout(add_dialog_panel);
        add_dialog_panel.setLayout(add_dialog_panelLayout);
        add_dialog_panelLayout.setHorizontalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_dialog_panelLayout.createSequentialGroup()
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, add_dialog_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(line_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(header_new_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, add_dialog_panelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nik_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nik_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employee_name_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employee_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                        .addComponent(level_label, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                        .addComponent(level_dropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(35, 35, 35)))
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departement_label, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(departement_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alamat_label, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password_fields))
                                .addGap(35, 35, 35)
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(no_telp_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(no_telp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(alamat_fields)))
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(14, 14, 14))
        );
        add_dialog_panelLayout.setVerticalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(header_new_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line_icon))
                .addGap(18, 18, 18)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nik_label)
                    .addComponent(employee_name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employee_name_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nik_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(level_label)
                    .addComponent(departement_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departement_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(level_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_dialog_panelLayout.createSequentialGroup()
                        .addComponent(no_telp_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no_telp_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addComponent(password_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(alamat_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamat_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout add_dialogLayout = new javax.swing.GroupLayout(add_dialog.getContentPane());
        add_dialog.getContentPane().setLayout(add_dialogLayout);
        add_dialogLayout.setHorizontalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        add_dialogLayout.setVerticalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(400, 600));

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_user.setPreferredSize(null);
        jScrollPane1.setViewportView(table_user);

        crud_panel.setBackground(new java.awt.Color(255, 255, 255));
        crud_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        crud_panel.setForeground(new java.awt.Color(204, 204, 204));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/plus.png"))); // NOI18N
        jButton1.setText("Add Employee");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crud_panelLayout = new javax.swing.GroupLayout(crud_panel);
        crud_panel.setLayout(crud_panelLayout);
        crud_panelLayout.setHorizontalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crud_panelLayout.setVerticalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        header_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Employee");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(crud_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(crud_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataTabel() {
//        dataUser.setVisible(false);
//        addUser.setVisible(true);
//           add_dialog.setModal(true);

        int row = table_user.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu.");
            return;
        }

//        jLabel2.setText("Perbarui Data Karyawan");

        // Ambil ID user dari tabel
        Object value = table_user.getModel().getValueAt(row, 0);
        int userId;
        if (value instanceof Integer) {
            userId = (int) value;
        } else {
            userId = Integer.parseInt(value.toString());
        }

        // Ambil data employee berdasarkan ID
        EmployeeModel userModel = userService.getById(userId);
        if (userModel == null) {
            JOptionPane.showMessageDialog(null, "Data user tidak ditemukan.");
            return;
        }

        // Query untuk ambil nama departemen dan level berdasarkan ID
        String sqldept = "SELECT deptname FROM departement WHERE iddept = ? AND isdeleted = 0";
        String sqllevel = "SELECT levelname FROM level WHERE idlevel = ? AND isdeleted = 0";

        String deptName = "";
        String levelName = "";

        try (
            PreparedStatement psDept = conn.prepareStatement(sqldept);
            PreparedStatement psLevel = conn.prepareStatement(sqllevel)
        ) {
            // Ambil deptname
            psDept.setInt(1, userModel.getIdDept());
            try (ResultSet rsDept = psDept.executeQuery()) {
                if (rsDept.next()) {
                    deptName = rsDept.getString("deptname");
                }
            }

            // Ambil levelname
            psLevel.setInt(1, userModel.getIdLevel());
            try (ResultSet rsLevel = psLevel.executeQuery()) {
                if (rsLevel.next()) {
                    levelName = rsLevel.getString("levelname");
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,
                "Terjadi kesalahan saat mengambil data departemen/level:\n" + e.getMessage());
        }
         // Set nilai ke input 
        password_fields.setText(""); // kosongkan password untuk keamanan
        employee_name_fields.setText(userModel.getEmployeeName());
        nik_fields.setText(userModel.getNik());
        alamat_fields.setText(userModel.getAddress());
        no_telp_fields.setText(userModel.getPhoneNumber());
        departement_dropdown.setSelectedItem(deptName);
        level_dropdown.setSelectedItem(levelName);

        // Aktifkan input form
//        active();
        add_on_modal.setText("Perbarui");
        cancel_on_modal.setVisible(true);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        add_dialog.pack();
        add_dialog.setLocationRelativeTo(null);
        add_dialog.setModal(true);
        add_dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nik_fieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nik_fieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nik_fieldsActionPerformed

    private void departement_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departement_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departement_dropdownActionPerformed

    private void level_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_level_dropdownActionPerformed

    private void no_telp_fieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_telp_fieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_telp_fieldsActionPerformed

    private void alamat_fieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat_fieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat_fieldsActionPerformed

    private void add_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_on_modalActionPerformed
        // TODO add your handling code here:
        createData();
    }//GEN-LAST:event_add_on_modalActionPerformed

    private void cancel_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_on_modalActionPerformed
        // TODO add your handling code here:
//        add_dialog.setModal(false);
        add_dialog.dispose();
    }//GEN-LAST:event_cancel_on_modalActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void loadData() {
//        btnHapus.setVisible(false);
//        btnBatal.setVisible(false);
        List<EmployeeModel> list = userService.getData();
        userTableModel.setData(list);
        userTableModel.fireTableDataChanged();

        table_user.getColumnModel().getColumn(0).setMinWidth(0);
        table_user.getColumnModel().getColumn(0).setMaxWidth(0);
        table_user.getColumnModel().getColumn(0).setWidth(0);
    }
    
    private void createData() {
        if(validasiInput()) {
            String nik = nik_fields.getText();
            String employeeName = employee_name_fields.getText();
            String address = alamat_fields.getText();
            String phoneNumber = no_telp_fields.getText();
            String deptName = departement_dropdown.getSelectedItem().toString();
            String levelName = level_dropdown.getSelectedItem().toString();
            String password = password_fields.getText();
            
            String sqlDept = "select iddept from departement where deptname=? and isdeleted=0";
            String sqlLevel = "select idlevel from level where levelname=? and isdeleted=0";
            
            Integer idDept = null;
            Integer idLevel = null;
            
            try {
                try(PreparedStatement stDept = conn.prepareStatement(sqlDept)) {
                    stDept.setString(1, deptName);
                    try(ResultSet rsDept = stDept.executeQuery()) {
                        if(rsDept.next()) {
                            idDept = rsDept.getInt("iddept");
                        } else {
                            JOptionPane.showMessageDialog(null, "Departement cannot found on database!");
                            return;
                        }
                    }
                } 
               
             
                 try(PreparedStatement stLevel = conn.prepareStatement(sqlLevel)) {
                     stLevel.setString(1, levelName);
                     try(ResultSet rsLevel = stLevel.executeQuery()) {
                         if(rsLevel.next()) {
                             idLevel = rsLevel.getInt("idlevel");
                         } else {
                             JOptionPane.showMessageDialog(null, "Level cannot found on database!");
                             return;
                         }
                     } 
                 }
                  
                EmployeeModel employeeModel = new EmployeeModel();
                employeeModel.setNik(nik);
                employeeModel.setAddress(address);
                employeeModel.setEmployeeName(employeeName);
                employeeModel.setIdDept(idDept);
                employeeModel.setIdLevel(idLevel);
                employeeModel.setPassword(password);
                employeeModel.setPhoneNumber(phoneNumber);
                
                userService.addEmployee(employeeModel);
                userTableModel.addUser(employeeModel);
                
                loadData();
                add_dialog.dispose();
                resetForm();
           } catch (Exception e) {
               e.printStackTrace();
               JOptionPane.showMessageDialog(null, "Failed Add Employee.");
           }
        }
    }

    
    private boolean validasiInput() {
        boolean valid = false;
        if(nik_fields.getText().isEmpty() || nik_fields.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "NIK cannot be null!");
        } else {
            valid = true;
        }
        
        return valid;
    }
    
    private void resetForm() {
        nik_fields.setText("");
        employee_name_fields.setText("");
        alamat_fields.setText("");
        no_telp_fields.setText("");
        password_fields.setText("");
        departement_dropdown.setSelectedIndex(0);
        level_dropdown.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog add_dialog;
    private javax.swing.JPanel add_dialog_panel;
    private javax.swing.JButton add_on_modal;
    private javax.swing.JTextField alamat_fields;
    private javax.swing.JLabel alamat_label;
    private javax.swing.JButton cancel_on_modal;
    private javax.swing.JPanel crud_panel;
    private javax.swing.JComboBox<String> departement_dropdown;
    private javax.swing.JLabel departement_label;
    private javax.swing.JTextField employee_name_fields;
    private javax.swing.JLabel employee_name_label;
    private javax.swing.JLabel header_new_employee;
    private javax.swing.JPanel header_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> level_dropdown;
    private javax.swing.JLabel level_label;
    private javax.swing.JLabel line_icon;
    private javax.swing.JTextField nik_fields;
    private javax.swing.JLabel nik_label;
    private javax.swing.JTextField no_telp_fields;
    private javax.swing.JLabel no_telp_label;
    private javax.swing.JPasswordField password_fields;
    private javax.swing.JLabel password_label;
    private javax.swing.JTable table_user;
    // End of variables declaration//GEN-END:variables
}
