/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.Koneksi;
import dao.OvertimeDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import model.OvertimeModel;
import tableModel.OvertimeTableModel;
import service.OvertimeService;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author wayan
 */
public class Overtime extends javax.swing.JPanel {

    private final OvertimeService overtimeservice = new OvertimeDAO();
    private final OvertimeTableModel overtimetablemodel = new OvertimeTableModel();
    private Connection conn = new Koneksi().koneksi();
    
    class ComboItem {
    private int id;
    private String name;

    public ComboItem(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return name; // akan muncul di combobox
    }
}

    public Overtime() {
        initComponents();
        
        
         //ADD EMPLOYEENAME COMBO BOX
        employee_dropdown.removeAllItems(); 

        String sql = "SELECT idemployee, employeename FROM employee where isdeleted = 0";

        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("idemployee");
                String name = rs.getString("employeename");
                employee_dropdown.addItem(new view.ComboItem(id, name).toString());
            }
            
            rs.close();
            ps.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        table_overtime.setModel(overtimetablemodel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_dialog = new javax.swing.JDialog();
        add_dialog_panel = new javax.swing.JPanel();
        header_new_overtime = new javax.swing.JLabel();
        line_icon = new javax.swing.JLabel();
        employee_dropdown = new javax.swing.JComboBox<>();
        employee_label = new javax.swing.JLabel();
        reason_field = new javax.swing.JTextField();
        reason_label = new javax.swing.JLabel();
        add_on_modal = new javax.swing.JButton();
        cancel_on_modal = new javax.swing.JButton();
        in_time_picker = new com.github.lgooddatepicker.components.TimePicker();
        ot_in_label = new javax.swing.JLabel();
        out_time_picker = new com.github.lgooddatepicker.components.TimePicker();
        ot_out_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_overtime = new javax.swing.JTable();
        crud_panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        header_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        add_dialog.setBackground(new java.awt.Color(255, 255, 255));

        add_dialog_panel.setBackground(new java.awt.Color(255, 255, 255));

        header_new_overtime.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        header_new_overtime.setText("New Overtime");

        line_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pipe.png"))); // NOI18N

        employee_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employee_dropdown.setPreferredSize(new java.awt.Dimension(64, 22));
        employee_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_dropdownActionPerformed(evt);
            }
        });

        employee_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employee_label.setText("Employee Name");

        reason_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reason_fieldActionPerformed(evt);
            }
        });

        reason_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reason_label.setText("Overtime Reason");

        add_on_modal.setText("Add");
        add_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_on_modalActionPerformed(evt);
            }
        });

        cancel_on_modal.setText("Cancel");
        cancel_on_modal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_on_modalActionPerformed(evt);
            }
        });

        ot_in_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ot_in_label.setText("Overtime In");

        ot_out_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ot_out_label.setText("Overtime Out");

        javax.swing.GroupLayout add_dialog_panelLayout = new javax.swing.GroupLayout(add_dialog_panel);
        add_dialog_panel.setLayout(add_dialog_panelLayout);
        add_dialog_panelLayout.setHorizontalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_dialog_panelLayout.createSequentialGroup()
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, add_dialog_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(line_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(header_new_overtime, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, add_dialog_panelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                .addComponent(employee_label, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(228, 604, Short.MAX_VALUE))
                            .addComponent(employee_dropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reason_field)
                            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                                        .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(in_time_picker, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ot_in_label, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(53, 53, 53)
                                        .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(out_time_picker, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ot_out_label, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(reason_label))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );
        add_dialog_panelLayout.setVerticalGroup(
            add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_dialog_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(header_new_overtime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line_icon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employee_label)
                .addGap(8, 8, 8)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addComponent(employee_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(ot_in_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(in_time_picker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_dialog_panelLayout.createSequentialGroup()
                        .addComponent(ot_out_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(out_time_picker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(reason_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reason_field, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(add_dialog_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_on_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout add_dialogLayout = new javax.swing.GroupLayout(add_dialog.getContentPane());
        add_dialog.getContentPane().setLayout(add_dialogLayout);
        add_dialogLayout.setHorizontalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        add_dialogLayout.setVerticalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_dialog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(400, 600));

        table_overtime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_overtime.setPreferredSize(null);
        table_overtime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_overtimeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_overtime);

        crud_panel.setBackground(new java.awt.Color(255, 255, 255));
        crud_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        crud_panel.setForeground(new java.awt.Color(204, 204, 204));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/plus.png"))); // NOI18N
        jButton1.setText("Add Overtime");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete (1).png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crud_panelLayout = new javax.swing.GroupLayout(crud_panel);
        crud_panel.setLayout(crud_panelLayout);
        crud_panelLayout.setHorizontalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crud_panelLayout.setVerticalGroup(
            crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crud_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(crud_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        header_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Overtime");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(crud_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(crud_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataTabel() {
//        dataClasses.setVisible(false);
//        addClasses.setVisible(true);
        
        employee_dropdown.setEnabled(false);

        int row = table_overtime.getSelectedRow();

        int overtimeid = (int) table_overtime.getModel().getValueAt(row, 0);
        OvertimeModel overtimemodel = overtimeservice.getById(overtimeid);
        
        String getemployeename = "SELECT employeename FROM employee WHERE employeename = ? AND isdeleted = 0";
        
        try {
            PreparedStatement psemployeename = conn.prepareStatement(getemployeename);
            psemployeename.setString(1, overtimemodel.getEmployeeName());
            ResultSet rsIdEmployee = psemployeename.executeQuery();

            String employeenamedata = null;
            if (rsIdEmployee.next()) {
                employeenamedata = rsIdEmployee.getString("employeename");
                
                // Set nilai ke input form
                employee_dropdown.setSelectedItem(employeenamedata);
                in_time_picker.setText(overtimemodel.getStartTime());
                out_time_picker.setText(overtimemodel.getEndTime());
                reason_field.setText(overtimemodel.getOvertimeReason());
                header_new_overtime.setText("Edit Overtime");
//                jLabel2.setText("Perbarui Data Lembur Karyawan");
                
            } else {
                JOptionPane.showMessageDialog(null, "Employee tidak ditemukan di database!");
                return;
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan saat memproses data batas Employee:\n" + e.getMessage());
        }

//        active();
//        add_on_modal.setText("Update");
//        btnBatalTambah.setVisible(true);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        if(jButton1.getText().equals("Edit Overtime")) {
            add_on_modal.setText("Update");
            dataTabel();
        } else {
            add_on_modal.setText("Add");
        }
        add_dialog.pack();
        add_dialog.setLocationRelativeTo(null);
        add_dialog.setModal(true);
        add_dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void employee_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employee_dropdownActionPerformed

    private void reason_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reason_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reason_fieldActionPerformed

    private void add_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_on_modalActionPerformed
        // TODO add your handling code here:
        if(add_on_modal.getText().equals("Add")) {
            createData();
        } else {
            updateData();
        }
    }//GEN-LAST:event_add_on_modalActionPerformed

    private void cancel_on_modalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_on_modalActionPerformed
        // TODO add your handling code here:
//        add_dialog.setModal(false);
        add_dialog.dispose();
        resetForm();
    }//GEN-LAST:event_cancel_on_modalActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
//        if (jButton1.getText().equals("Edit Employee")) {
//            dataTabel();
//        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void table_overtimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_overtimeMouseClicked
        // TODO add your handling code here:
        if(jButton1.getText().equals("Add Overtime")) {
            jButton1.setText("Edit Overtime");
        }
        
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    }//GEN-LAST:event_table_overtimeMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        loadData();
        resetForm();
    }//GEN-LAST:event_jButton3ActionPerformed

//    private void active() {
//        txtNotes.setEnabled(true);
//    }

    private void loadData() {
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton1.setText("Add Overtime");
        employee_dropdown.setEnabled(true);
        List<OvertimeModel> list = overtimeservice.getData();
        overtimetablemodel.setData(list); 

        table_overtime.getColumnModel().getColumn(0).setMinWidth(0);
        table_overtime.getColumnModel().getColumn(0).setMaxWidth(0);
        table_overtime.getColumnModel().getColumn(0).setWidth(0);
    }


   private void createData() {
        if (validasiInput()) {
            String getemployeename = (String) employee_dropdown.getSelectedItem();
            String startText = in_time_picker.getText();
            String endText = out_time_picker.getText();
            
            try {
                // Ambil tanggal sekarang (tanpa waktu)
                LocalDate today = LocalDate.now();
                String checkingdoubledata = "select o.idovertime,o.idemployeeovertime,e.employeename,o.overtimereason,o.starttime,o.endtime,o.duration,\n" +
                                            "date(o.created_at) as overtimedate  from overtime as o\n" +
                                            "left join employee as e on o.idemployeeovertime = e.idemployee WHERE o.isdeleted = 0 AND DATE(o.created_at) = ?";
                PreparedStatement psDouble = conn.prepareStatement(checkingdoubledata);
                psDouble.setDate(1, java.sql.Date.valueOf(today)); 

                ResultSet rsdouble = psDouble.executeQuery();

                if (rsdouble.next()) {
                    String existingName = rsdouble.getString("employeename");
                    if(existingName.equalsIgnoreCase(getemployeename)){
                        JOptionPane.showMessageDialog(null, "Overtime data for " + existingName + " is available today.");
                        rsdouble.close();
                        psDouble.close();
                        return;
                    }
                }

                rsdouble.close();
                psDouble.close();

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal memeriksa data lembur ganda.");
                return;
            }

            // Formatter untuk 12 jam dan 24 jam
            DateTimeFormatter formatter12Hour = DateTimeFormatter.ofPattern("h:mma");
            DateTimeFormatter formatter24Hour = DateTimeFormatter.ofPattern("H:mm");

            LocalTime start = null;
            LocalTime end = null;

            try {
                start = LocalTime.parse(startText.toUpperCase(), formatter12Hour);
            } catch (Exception e) {
                start = LocalTime.parse(startText, formatter24Hour);
            }

            try {
                end = LocalTime.parse(endText.toUpperCase(), formatter12Hour);
            } catch (Exception e) {
                end = LocalTime.parse(endText, formatter24Hour);
            }

            long durationInMinutes = ChronoUnit.MINUTES.between(start, end);
            if (durationInMinutes < 0) {
                durationInMinutes += 1440; // Jika end < start, tambahkan 24 jam
            }

            // Validasi minimal 1 jam
            if (durationInMinutes < 60) {
                JOptionPane.showMessageDialog(null, "The duration of overtime must not be less than 1 hour.");
                return;
            }

            Integer deptname = null;
            String endTimeStr = "";

            try {
                // Ambil deptname berdasarkan employeename
                String sqlDept = "SELECT iddeptemployee FROM employee WHERE employeename = ? and isdeleted=0";
                PreparedStatement psDept = conn.prepareStatement(sqlDept);
                psDept.setString(1, getemployeename);
                ResultSet rsDept = psDept.executeQuery();

                if (rsDept.next()) {
                    deptname = rsDept.getInt("iddeptemployee");
                } else {
                    JOptionPane.showMessageDialog(null, "Departemen tidak ditemukan untuk karyawan ini.");
                    rsDept.close();
                    psDept.close();
                    return;
                }

                rsDept.close();
                psDept.close();

                // Ambil endtimestr dari threshold
                String sqlThreshold = "SELECT endtimestr FROM threshold WHERE iddeptthreshold = ? AND attendancename = 'OUT' and isdeleted = 0";
                PreparedStatement psThresh = conn.prepareStatement(sqlThreshold);
                psThresh.setInt(1, deptname);
                ResultSet rsThresh = psThresh.executeQuery();
                
                if (rsThresh.next()) {
                    endTimeStr = rsThresh.getString("endtimestr");
                } else {
                    JOptionPane.showMessageDialog(null, "Threshold untuk departemen ini tidak ditemukan.");
                    rsThresh.close();
                    psThresh.close();
                    return;
                }
                
                rsThresh.close();
                psThresh.close();

                // Parse endTimeStr dari threshold ke LocalTime
                LocalTime thresholdEnd = LocalTime.parse(endTimeStr.toUpperCase(), formatter12Hour);

                // Validasi: end tidak boleh lebih awal dari thresholdEnd
                if (end.isBefore(thresholdEnd)) {
                    JOptionPane.showMessageDialog(null, "Jam selesai lembur tidak boleh lebih awal dari waktu OUT (" + endTimeStr + ").");
                    return;
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengambil data departemen atau threshold.");
                return;
            }

            // Simpan data ke model
            
            try {
                String getidemployee = "SELECT idemployee FROM employee where isdeleted = 0 and employeename = ?";
                PreparedStatement idemployee = conn.prepareStatement(getidemployee);
                idemployee.setString(1, getemployeename); 

                ResultSet rsgetidemployee = idemployee.executeQuery();

                if (rsgetidemployee.next()) {
                    OvertimeModel overtimemodel = new OvertimeModel();
                    overtimemodel.setIdEmployee(rsgetidemployee.getInt("idemployee"));
                    overtimemodel.setStartTime(startText);
                    overtimemodel.setEndTime(endText);
                    overtimemodel.setOvertimeReason(reason_field.getText());
                    overtimemodel.setDuration((int) durationInMinutes);

                    overtimeservice.addOvertime(overtimemodel);
                    overtimetablemodel.addOvertime(overtimemodel);
                    
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal mendapatkan data ID karyawan.");
                return;
            }
            loadData();
            resetForm();
            add_dialog.dispose();
//            showPanel();
            add_on_modal.setText("Add");
        }
    }

    private void updateData() {
        int row = table_overtime.getSelectedRow();
        if (row != -1) {
            if (validasiInput()) {
                String getemployeename = (String) employee_dropdown.getSelectedItem();
                String startText = in_time_picker.getText();
                String endText = out_time_picker.getText();

                // PENTING: Buat model SEKALI SAJA
                OvertimeModel overtimemodel = new OvertimeModel();
                overtimemodel.setId((int) table_overtime.getModel().getValueAt(row, 0));

                try {
                    // Cek apakah lembur untuk karyawan ini sudah ada di tanggal yang sama (kecuali ID yang sedang diedit)
                    LocalDate today = LocalDate.now();
                    String checkingdoubledata = "select o.idovertime,o.idemployeeovertime,e.employeename,o.overtimereason,o.starttime,o.endtime,o.duration,\n" +
                                            "date(o.created_at) as overtimedate  from overtime as o\n" +
                                            "left join employee as e on o.idemployeeovertime = e.idemployee WHERE o.isdeleted = 0 AND DATE(o.created_at) = ? AND e.employeename != ?";                    
                    PreparedStatement psDouble = conn.prepareStatement(checkingdoubledata);
                    psDouble.setDate(1, java.sql.Date.valueOf(today));
                    psDouble.setString(2, getemployeename);

                    ResultSet rsdouble = psDouble.executeQuery();

                    while (rsdouble.next()) {
                        int idexisting = rsdouble.getInt("idovertime");
                        if (idexisting != overtimemodel.getId()) {
                            JOptionPane.showMessageDialog(null, "Overtime data for " + getemployeename + " is available today.");
                            rsdouble.close();
                            psDouble.close();
                            return;
                        }
                    }

                    rsdouble.close();
                    psDouble.close();

                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Gagal memeriksa data lembur ganda.");
                    return;
                }

                // Format waktu
                DateTimeFormatter formatter12Hour = DateTimeFormatter.ofPattern("h:mma");
                DateTimeFormatter formatter24Hour = DateTimeFormatter.ofPattern("H:mm");

                LocalTime start, end;
                try {
                    start = LocalTime.parse(startText.toUpperCase(), formatter12Hour);
                } catch (Exception e) {
                    start = LocalTime.parse(startText, formatter24Hour);
                }

                try {
                    end = LocalTime.parse(endText.toUpperCase(), formatter12Hour);
                } catch (Exception e) {
                    end = LocalTime.parse(endText, formatter24Hour);
                }

                long durationInMinutes = ChronoUnit.MINUTES.between(start, end);
                if (durationInMinutes < 0) durationInMinutes += 1440;

                if (durationInMinutes < 60) {
                    JOptionPane.showMessageDialog(null, "The duration of overtime must not be less than 1 hour.");
                    return;
                }

                // Validasi terhadap threshold
                try {
                    Integer iddept = null;
                    String thresholdStr = "";

                    // Ambil departemen
                    String sqlDept = "SELECT iddeptemployee FROM employee WHERE employeename = ? and isdeleted = 0";
                    PreparedStatement psDept = conn.prepareStatement(sqlDept);
                    psDept.setString(1, getemployeename);
                    ResultSet rsDept = psDept.executeQuery();

                    if (rsDept.next()) {
                        iddept = rsDept.getInt("iddeptemployee");
                    } else {
                        JOptionPane.showMessageDialog(null, "Departemen tidak ditemukan.");
                        rsDept.close();
                        psDept.close();
                        return;
                    }
                    rsDept.close();
                    psDept.close();

                    // Ambil threshold end time
                    String sqlThresh = "SELECT endtimestr FROM threshold WHERE iddeptthreshold = ? AND attendancename = 'OUT' and isdeleted = 0";
                    PreparedStatement psThresh = conn.prepareStatement(sqlThresh);
                    psThresh.setInt(1, iddept);
                    ResultSet rsThresh = psThresh.executeQuery();

                    if (rsThresh.next()) {
                        thresholdStr = rsThresh.getString("endtimestr");
                    } else {
                        JOptionPane.showMessageDialog(null, "Threshold tidak ditemukan untuk departemen ini.");
                        rsThresh.close();
                        psThresh.close();
                        return;
                    }
                    rsThresh.close();
                    psThresh.close();

                    // Bandingkan waktu selesai lembur dengan threshold
                    LocalTime thresholdEnd = LocalTime.parse(thresholdStr.toUpperCase(), formatter12Hour);
                    if (end.isBefore(thresholdEnd)) {
                        JOptionPane.showMessageDialog(null, "Jam selesai lembur tidak boleh lebih awal dari waktu OUT (" + thresholdStr + ").");
                        return;
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Gagal melakukan validasi threshold.");
                    return;
                }
                
                try {
                String getidemployee = "SELECT idemployee FROM employee where isdeleted = 0 and employeename = ?";
                PreparedStatement idemployee = conn.prepareStatement(getidemployee);
                idemployee.setString(1, getemployeename); 

                ResultSet rsgetidemployee = idemployee.executeQuery();

                if (rsgetidemployee.next()) {
                    // Simpan data jika semua validasi lolos
                    overtimemodel.setIdEmployee(rsgetidemployee.getInt("idemployee"));
                    overtimemodel.setStartTime(startText);
                    overtimemodel.setEndTime(endText);
                    overtimemodel.setOvertimeReason(reason_field.getText());
                    overtimemodel.setDuration((int) durationInMinutes);

                    overtimeservice.editOvertime(overtimemodel);
                    overtimetablemodel.editOvertime(row, overtimemodel);
                    loadData();
                    resetForm();
                    add_dialog.dispose();
//                    showPanel();
                 
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Failed Get ID Employee.");
                return;
            }

              
            }
        }
    }
    
    private void deleteData() {
        int index = table_overtime.getSelectedRow();
        if (index != -1) {
            int deptId = (int) table_overtime.getModel().getValueAt(index, 0);
            OvertimeModel getovertime = overtimeservice.getById(deptId);

            OvertimeModel overtimemodel = getovertime;

            if (JOptionPane.showConfirmDialog(null, "Are you sure, you want delete this data?", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                overtimeservice.deleteOvertime(overtimemodel);
                overtimetablemodel.deleteOvertime(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select");
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (reason_field.getText().trim().isEmpty() || in_time_picker.getTime() == null || out_time_picker.getTime() == null) {
            JOptionPane.showMessageDialog(null, "Please fill all field.");
        } else {
            valid = true;
        }

        return valid;
    }

//    private void showPanel() {
//        mainPanel.removeAll();
//        mainPanel.add(new FormOvertime());
//        mainPanel.repaint();
//        mainPanel.revalidate();
//    }

    private void resetForm() {
//        btnTambah.requestFocus();
//        jButton1.setText("Add Overtime");
        header_new_overtime.setText("New Overtime");
        reason_field.setText("");
        in_time_picker.setTime(null);
        out_time_picker.setTime(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog add_dialog;
    private javax.swing.JPanel add_dialog_panel;
    private javax.swing.JButton add_on_modal;
    private javax.swing.JButton cancel_on_modal;
    private javax.swing.JPanel crud_panel;
    private javax.swing.JComboBox<String> employee_dropdown;
    private javax.swing.JLabel employee_label;
    private javax.swing.JLabel header_new_overtime;
    private javax.swing.JPanel header_panel;
    private com.github.lgooddatepicker.components.TimePicker in_time_picker;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel line_icon;
    private javax.swing.JLabel ot_in_label;
    private javax.swing.JLabel ot_out_label;
    private com.github.lgooddatepicker.components.TimePicker out_time_picker;
    private javax.swing.JTextField reason_field;
    private javax.swing.JLabel reason_label;
    private javax.swing.JTable table_overtime;
    // End of variables declaration//GEN-END:variables
}
