/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.Koneksi;
import dao.OvertimeDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import model.OvertimeModel;
import tableModel.OvertimeTableModel;
import service.OvertimeService;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author wayan
 */
public class Overtime extends javax.swing.JPanel {

    private final OvertimeService overtimeservice = new OvertimeDAO();
    private final OvertimeTableModel overtimetablemodel = new OvertimeTableModel();
    private Connection conn = new Koneksi().koneksi();
    
    class ComboItem {
    private int id;
    private String name;

    public ComboItem(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return name; // akan muncul di combobox
    }
}

    public Overtime() {
        initComponents();
        
        
         //ADD EMPLOYEENAME COMBO BOX
        employeename.removeAllItems(); 

        String sql = "SELECT idemployee, employeename FROM employee where isdeleted = 0";

        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("idemployee");
                String name = rs.getString("employeename");
                employeename.addItem(new view.ComboItem(id, name).toString());
            }
            
            rs.close();
            ps.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        tblOvertime.setModel(overtimetablemodel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataClasses = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOvertime = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        addClasses = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatalTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        employeename = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        endtime = new com.github.lgooddatepicker.components.TimePicker();
        starttime = new com.github.lgooddatepicker.components.TimePicker();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(899, 620));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataClasses.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblOvertime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOvertime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOvertimeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOvertime);

        jLabel1.setText("Data Lembur Karyawan");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N

        btnTambah.setText("Tambah");
        btnTambah.setPreferredSize(new java.awt.Dimension(85, 30));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setPreferredSize(new java.awt.Dimension(85, 30));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.setPreferredSize(new java.awt.Dimension(85, 30));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataClassesLayout = new javax.swing.GroupLayout(dataClasses);
        dataClasses.setLayout(dataClassesLayout);
        dataClassesLayout.setHorizontalGroup(
            dataClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataClassesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(dataClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataClassesLayout.setVerticalGroup(
            dataClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(dataClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataClasses, "card2");

        addClasses.setBackground(new java.awt.Color(255, 255, 255));
        addClasses.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setText("Tambah Data Lembur");
        addClasses.add(jLabel2);
        jLabel2.setBounds(6, 6, 887, 36);

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setText("Tambah");
        btnSimpan.setPreferredSize(new java.awt.Dimension(74, 30));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        addClasses.add(btnSimpan);
        btnSimpan.setBounds(708, 73, 85, 30);

        btnBatalTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBatalTambah.setText("Batal");
        btnBatalTambah.setPreferredSize(new java.awt.Dimension(85, 30));
        btnBatalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTambahActionPerformed(evt);
            }
        });
        addClasses.add(btnBatalTambah);
        btnBatalTambah.setBounds(811, 73, 85, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Nama Karyawan");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        txtNotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNotes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(76, 122, 227)));
        txtNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotesActionPerformed(evt);
            }
        });

        employeename.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Jam Mulai");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        jLabel5.setText("Jam Selesai");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        jLabel6.setText("Alasan ");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(employeename, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(314, 314, 314)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(starttime, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(233, 233, 233)
                                .addComponent(endtime, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeename, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(starttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(548, Short.MAX_VALUE))
        );

        addClasses.add(jPanel1);
        jPanel1.setBounds(0, 121, 902, 830);

        mainPanel.add(addClasses, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void dataTabel() {
        dataClasses.setVisible(false);
        addClasses.setVisible(true);

        int row = tblOvertime.getSelectedRow();

        int overtimeid = (int) tblOvertime.getModel().getValueAt(row, 0);
        OvertimeModel overtimemodel = overtimeservice.getById(overtimeid);
        
        String getemployeename = "SELECT employeename FROM employee WHERE employeename = ? AND isdeleted = 0";
        
        try {
            PreparedStatement psemployeename = conn.prepareStatement(getemployeename);
            psemployeename.setString(1, overtimemodel.getEmployeeName());
            ResultSet rsIdEmployee = psemployeename.executeQuery();

            String employeenamedata = null;
            if (rsIdEmployee.next()) {
                employeenamedata = rsIdEmployee.getString("employeename");
                
                // Set nilai ke input form
                employeename.setSelectedItem(employeenamedata);
                starttime.setText(overtimemodel.getStartTime());
                endtime.setText(overtimemodel.getEndTime());
                txtNotes.setText(overtimemodel.getOvertimeReason());
                jLabel2.setText("Perbarui Data Lembur Karyawan");
                
            } else {
                JOptionPane.showMessageDialog(null, "Departemen tidak ditemukan di database!");
                return;
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan saat memproses data batas deptname:\n" + e.getMessage());
        }

        active();
        btnSimpan.setText("Perbarui");
        btnBatalTambah.setVisible(true);
    }

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(addClasses);
        mainPanel.repaint();
        mainPanel.revalidate();

        btnSimpan.setText("Simpan");
        if (btnTambah.getText().equals("Ubah")) {
            dataTabel();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBatalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTambahActionPerformed
        showPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btnBatalTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        switch (btnSimpan.getText()) {
            case "Tambah" ->
                btnSimpan.setText("Simpan");
            case "Simpan" ->
                createData();
            case "Perbarui" ->
                updateData();
            default -> {
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblOvertimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOvertimeMouseClicked
        if (btnTambah.getText().equals("Tambah")) {
            btnTambah.setText("Ubah");
        }

        btnHapus.setVisible(true);
        btnBatal.setVisible(true);
    }//GEN-LAST:event_tblOvertimeMouseClicked

    private void txtNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotesActionPerformed

    private void active() {
        txtNotes.setEnabled(true);
    }

    private void loadData() {
        btnHapus.setVisible(false);
        btnBatal.setVisible(false);
        List<OvertimeModel> list = overtimeservice.getData();
        overtimetablemodel.setData(list); 

        tblOvertime.getColumnModel().getColumn(0).setMinWidth(0);
        tblOvertime.getColumnModel().getColumn(0).setMaxWidth(0);
        tblOvertime.getColumnModel().getColumn(0).setWidth(0);
    }


   private void createData() {
        if (validasiInput()) {
            String getemployeename = (String) employeename.getSelectedItem();
            String startText = starttime.getText();
            String endText = endtime.getText();
            
            try {
                // Ambil tanggal sekarang (tanpa waktu)
                LocalDate today = LocalDate.now();
                String checkingdoubledata = "select o.idovertime,o.idemployeeovertime,e.employeename,o.overtimereason,o.starttime,o.endtime,o.duration,\n" +
                                            "date(o.created_at) as overtimedate  from overtime as o\n" +
                                            "left join employee as e on o.idemployeeovertime = e.idemployee WHERE o.isdeleted = 0 AND DATE(o.created_at) = ?";
                PreparedStatement psDouble = conn.prepareStatement(checkingdoubledata);
                psDouble.setDate(1, java.sql.Date.valueOf(today)); 

                ResultSet rsdouble = psDouble.executeQuery();

                if (rsdouble.next()) {
                    String existingName = rsdouble.getString("employeename");
                    if(existingName.equalsIgnoreCase(getemployeename)){
                        JOptionPane.showMessageDialog(null, "Data lembur untuk " + existingName + " sudah ada hari ini.");
                        rsdouble.close();
                        psDouble.close();
                        return;
                    }
                }

                rsdouble.close();
                psDouble.close();

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal memeriksa data lembur ganda.");
                return;
            }

            // Formatter untuk 12 jam dan 24 jam
            DateTimeFormatter formatter12Hour = DateTimeFormatter.ofPattern("h:mma");
            DateTimeFormatter formatter24Hour = DateTimeFormatter.ofPattern("H:mm");

            LocalTime start = null;
            LocalTime end = null;

            try {
                start = LocalTime.parse(startText.toUpperCase(), formatter12Hour);
            } catch (Exception e) {
                start = LocalTime.parse(startText, formatter24Hour);
            }

            try {
                end = LocalTime.parse(endText.toUpperCase(), formatter12Hour);
            } catch (Exception e) {
                end = LocalTime.parse(endText, formatter24Hour);
            }

            long durationInMinutes = ChronoUnit.MINUTES.between(start, end);
            if (durationInMinutes < 0) {
                durationInMinutes += 1440; // Jika end < start, tambahkan 24 jam
            }

            // Validasi minimal 1 jam
            if (durationInMinutes < 60) {
                JOptionPane.showMessageDialog(null, "Durasi lembur minimal 1 jam.");
                return;
            }

            Integer deptname = null;
            String endTimeStr = "";

            try {
                // Ambil deptname berdasarkan employeename
                String sqlDept = "SELECT iddeptemployee FROM employee WHERE employeename = ? and isdeleted=0";
                PreparedStatement psDept = conn.prepareStatement(sqlDept);
                psDept.setString(1, getemployeename);
                ResultSet rsDept = psDept.executeQuery();

                if (rsDept.next()) {
                    deptname = rsDept.getInt("iddeptemployee");
                } else {
                    JOptionPane.showMessageDialog(null, "Departemen tidak ditemukan untuk karyawan ini.");
                    rsDept.close();
                    psDept.close();
                    return;
                }

                rsDept.close();
                psDept.close();

                // Ambil endtimestr dari threshold
                String sqlThreshold = "SELECT endtimestr FROM threshold WHERE iddeptthreshold = ? AND attendancename = 'OUT' and isdeleted = 0";
                PreparedStatement psThresh = conn.prepareStatement(sqlThreshold);
                psThresh.setInt(1, deptname);
                ResultSet rsThresh = psThresh.executeQuery();
                
                if (rsThresh.next()) {
                    endTimeStr = rsThresh.getString("endtimestr");
                } else {
                    JOptionPane.showMessageDialog(null, "Threshold untuk departemen ini tidak ditemukan.");
                    rsThresh.close();
                    psThresh.close();
                    return;
                }
                
                rsThresh.close();
                psThresh.close();

                // Parse endTimeStr dari threshold ke LocalTime
                LocalTime thresholdEnd = LocalTime.parse(endTimeStr.toUpperCase(), formatter12Hour);

                // Validasi: end tidak boleh lebih awal dari thresholdEnd
                if (end.isBefore(thresholdEnd)) {
                    JOptionPane.showMessageDialog(null, "Jam selesai lembur tidak boleh lebih awal dari waktu OUT (" + endTimeStr + ").");
                    return;
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengambil data departemen atau threshold.");
                return;
            }

            // Simpan data ke model
            
            try {
                String getidemployee = "SELECT idemployee FROM employee where isdeleted = 0 and employeename = ?";
                PreparedStatement idemployee = conn.prepareStatement(getidemployee);
                idemployee.setString(1, getemployeename); 

                ResultSet rsgetidemployee = idemployee.executeQuery();

                if (rsgetidemployee.next()) {
                    OvertimeModel overtimemodel = new OvertimeModel();
                    overtimemodel.setIdEmployee(rsgetidemployee.getInt("idemployee"));
                    overtimemodel.setStartTime(startText);
                    overtimemodel.setEndTime(endText);
                    overtimemodel.setOvertimeReason(txtNotes.getText());
                    overtimemodel.setDuration((int) durationInMinutes);

                    overtimeservice.addOvertime(overtimemodel);
                    overtimetablemodel.addOvertime(overtimemodel);
                    
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal mendapatkan data ID karyawan.");
                return;
            }
            loadData();
            resetForm();
            showPanel();
            btnSimpan.setText("Tambah");
        }
    }

    private void updateData() {
        int row = tblOvertime.getSelectedRow();
        if (row != -1) {
            if (validasiInput()) {
                String getemployeename = (String) employeename.getSelectedItem();
                String startText = starttime.getText();
                String endText = endtime.getText();

                // PENTING: Buat model SEKALI SAJA
                OvertimeModel overtimemodel = new OvertimeModel();
                overtimemodel.setId((int) tblOvertime.getModel().getValueAt(row, 0));

                try {
                    // Cek apakah lembur untuk karyawan ini sudah ada di tanggal yang sama (kecuali ID yang sedang diedit)
                    LocalDate today = LocalDate.now();
                    String checkingdoubledata = "select o.idovertime,o.idemployeeovertime,e.employeename,o.overtimereason,o.starttime,o.endtime,o.duration,\n" +
                                            "date(o.created_at) as overtimedate  from overtime as o\n" +
                                            "left join employee as e on o.idemployeeovertime = e.idemployee WHERE o.isdeleted = 0 AND DATE(o.created_at) = ? AND e.employeename != ?";                    
                    PreparedStatement psDouble = conn.prepareStatement(checkingdoubledata);
                    psDouble.setDate(1, java.sql.Date.valueOf(today));
                    psDouble.setString(2, getemployeename);

                    ResultSet rsdouble = psDouble.executeQuery();

                    while (rsdouble.next()) {
                        int idexisting = rsdouble.getInt("idovertime");
                        if (idexisting != overtimemodel.getId()) {
                            JOptionPane.showMessageDialog(null, "Data lembur untuk " + getemployeename + " sudah ada hari ini.");
                            rsdouble.close();
                            psDouble.close();
                            return;
                        }
                    }

                    rsdouble.close();
                    psDouble.close();

                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Gagal memeriksa data lembur ganda.");
                    return;
                }

                // Format waktu
                DateTimeFormatter formatter12Hour = DateTimeFormatter.ofPattern("h:mma");
                DateTimeFormatter formatter24Hour = DateTimeFormatter.ofPattern("H:mm");

                LocalTime start, end;
                try {
                    start = LocalTime.parse(startText.toUpperCase(), formatter12Hour);
                } catch (Exception e) {
                    start = LocalTime.parse(startText, formatter24Hour);
                }

                try {
                    end = LocalTime.parse(endText.toUpperCase(), formatter12Hour);
                } catch (Exception e) {
                    end = LocalTime.parse(endText, formatter24Hour);
                }

                long durationInMinutes = ChronoUnit.MINUTES.between(start, end);
                if (durationInMinutes < 0) durationInMinutes += 1440;

                if (durationInMinutes < 60) {
                    JOptionPane.showMessageDialog(null, "Durasi lembur tidak boleh kurang dari 1 jam.");
                    return;
                }

                // Validasi terhadap threshold
                try {
                    Integer iddept = null;
                    String thresholdStr = "";

                    // Ambil departemen
                    String sqlDept = "SELECT iddeptemployee FROM employee WHERE employeename = ? and isdeleted = 0";
                    PreparedStatement psDept = conn.prepareStatement(sqlDept);
                    psDept.setString(1, getemployeename);
                    ResultSet rsDept = psDept.executeQuery();

                    if (rsDept.next()) {
                        iddept = rsDept.getInt("iddeptemployee");
                    } else {
                        JOptionPane.showMessageDialog(null, "Departemen tidak ditemukan.");
                        rsDept.close();
                        psDept.close();
                        return;
                    }
                    rsDept.close();
                    psDept.close();

                    // Ambil threshold end time
                    String sqlThresh = "SELECT endtimestr FROM threshold WHERE iddeptthreshold = ? AND attendancename = 'OUT' and isdeleted = 0";
                    PreparedStatement psThresh = conn.prepareStatement(sqlThresh);
                    psThresh.setInt(1, iddept);
                    ResultSet rsThresh = psThresh.executeQuery();

                    if (rsThresh.next()) {
                        thresholdStr = rsThresh.getString("endtimestr");
                    } else {
                        JOptionPane.showMessageDialog(null, "Threshold tidak ditemukan untuk departemen ini.");
                        rsThresh.close();
                        psThresh.close();
                        return;
                    }
                    rsThresh.close();
                    psThresh.close();

                    // Bandingkan waktu selesai lembur dengan threshold
                    LocalTime thresholdEnd = LocalTime.parse(thresholdStr.toUpperCase(), formatter12Hour);
                    if (end.isBefore(thresholdEnd)) {
                        JOptionPane.showMessageDialog(null, "Jam selesai lembur tidak boleh lebih awal dari waktu OUT (" + thresholdStr + ").");
                        return;
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Gagal melakukan validasi threshold.");
                    return;
                }
                
                try {
                String getidemployee = "SELECT idemployee FROM employee where isdeleted = 0 and employeename = ?";
                PreparedStatement idemployee = conn.prepareStatement(getidemployee);
                idemployee.setString(1, getemployeename); 

                ResultSet rsgetidemployee = idemployee.executeQuery();

                if (rsgetidemployee.next()) {
                    // Simpan data jika semua validasi lolos
                    overtimemodel.setIdEmployee(rsgetidemployee.getInt("idemployee"));
                    overtimemodel.setStartTime(startText);
                    overtimemodel.setEndTime(endText);
                    overtimemodel.setOvertimeReason(txtNotes.getText());
                    overtimemodel.setDuration((int) durationInMinutes);

                    overtimeservice.editOvertime(overtimemodel);
                    overtimetablemodel.editOvertime(row, overtimemodel);
                    loadData();
                    resetForm();
                    showPanel();
                 
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal mendapatkan data ID karyawan.");
                return;
            }

              
            }
        }
    }
    
    private void deleteData() {
        int index = tblOvertime.getSelectedRow();
        if (index != -1) {
            int deptId = (int) tblOvertime.getModel().getValueAt(index, 0);
            OvertimeModel getovertime = overtimeservice.getById(deptId);

            OvertimeModel overtimemodel = getovertime;

            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                overtimeservice.deleteOvertime(overtimemodel);
                overtimetablemodel.deleteOvertime(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (txtNotes.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Notes tidak boleh kosong");
        } else {
            valid = true;
        }

        return valid;
    }

    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Overtime());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void resetForm() {
        btnTambah.requestFocus();
        btnTambah.setText("Tambah");
        txtNotes.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addClasses;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatalTambah;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel dataClasses;
    private javax.swing.JComboBox<String> employeename;
    private com.github.lgooddatepicker.components.TimePicker endtime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private com.github.lgooddatepicker.components.TimePicker starttime;
    private javax.swing.JTable tblOvertime;
    private javax.swing.JTextField txtNotes;
    // End of variables declaration//GEN-END:variables
}
