/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hrms;

import config.Koneksi;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.BoxLayout;
import model.LoginModel;
import view.Employee;
import view.Login;
import view.Level;

/**
 *
 * @author USer
 */
public class MainMenu extends javax.swing.JFrame {
    private String nik;
    private String nama;
    private final Connection conn = Koneksi.koneksi();

    /**
     * Creates new form MainMenu
     */
    public MainMenu(String nik, String nama) {
        initComponents();
        menu_panel.setLayout(new BoxLayout(menu_panel, javax.swing.BoxLayout.Y_AXIS));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        this.nik = nik;
        this.nama = nama;
//        
//        System.out.println("Nik dari menu utama" + nik);

          user.setText(nama);
          executed(nik);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar_panel = new javax.swing.JPanel();
        menu_panel = new javax.swing.JPanel();
        main_content_panel = new javax.swing.JPanel();
        headers_panel = new javax.swing.JPanel();
        logo_sts = new javax.swing.JLabel();
        user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1920, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        sidebar_panel.setBackground(new java.awt.Color(255, 255, 255));
        sidebar_panel.setPreferredSize(new java.awt.Dimension(300, 300));

        menu_panel.setBackground(new java.awt.Color(255, 255, 255));
        menu_panel.setPreferredSize(new java.awt.Dimension(300, 300));
        menu_panel.setLayout(new javax.swing.BoxLayout(menu_panel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout sidebar_panelLayout = new javax.swing.GroupLayout(sidebar_panel);
        sidebar_panel.setLayout(sidebar_panelLayout);
        sidebar_panelLayout.setHorizontalGroup(
            sidebar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar_panelLayout.createSequentialGroup()
                .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidebar_panelLayout.setVerticalGroup(
            sidebar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_content_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_content_panel.setLayout(new java.awt.GridLayout(1, 2));

        headers_panel.setBackground(new java.awt.Color(51, 102, 255));

        logo_sts.setBackground(new java.awt.Color(255, 255, 255));
        logo_sts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/STS LOGO 1 (1).png"))); // NOI18N

        user.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mn_user.png"))); // NOI18N
        user.setText("USER");

        javax.swing.GroupLayout headers_panelLayout = new javax.swing.GroupLayout(headers_panel);
        headers_panel.setLayout(headers_panelLayout);
        headers_panelLayout.setHorizontalGroup(
            headers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headers_panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(logo_sts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 557, Short.MAX_VALUE)
                .addComponent(user)
                .addGap(28, 28, 28))
        );
        headers_panelLayout.setVerticalGroup(
            headers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headers_panelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(logo_sts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headers_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(user)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sidebar_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(main_content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addComponent(headers_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(headers_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebar_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(main_content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        main_content_panel.add(new ContentBg());
        main_content_panel.repaint();
        main_content_panel.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
//            public void run() {
////                new MainMenu().setVisible(true);
//            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headers_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo_sts;
    private javax.swing.JPanel main_content_panel;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JPanel sidebar_panel;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
    
     private void executed(String nik) {
        // Icon Master
        ImageIcon masterIcon = new ImageIcon(getClass().getResource("/assets/master_icon.png"));
        ImageIcon dashboardIcon = new ImageIcon(getClass().getResource("/assets/dashboard_icon.png"));
//        ImageIcon reportIcon = new ImageIcon(getClass().getResource("/asset/img/report_icon.png"));
//        ImageIcon registIcon = new ImageIcon(getClass().getResource("/asset/img/regist_icon.png"));
//        ImageIcon scheduleIcon = new ImageIcon(getClass().getResource("/asset/img/schedule_icon.png"));
//        ImageIcon subIcon = new ImageIcon(getClass().getResource("/assets/sort_icon.png"));
//        ImageIcon logoutIcon = new ImageIcon(getClass().getResource("/asset/img/logout_icon.png"));
        ImageIcon rightArrow = new ImageIcon(getClass().getResource("/assets/next.png"));
        ImageIcon downArrow = new ImageIcon(getClass().getResource("/assets/down.png"));

        MenuItem menuDashboard = new MenuItem(dashboardIcon, false, null, null, null, "Dashboard", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main_content_panel.removeAll();
                main_content_panel.add(new ContentBg(), BorderLayout.CENTER);
                main_content_panel.repaint();
                main_content_panel.revalidate();
            }
        });

        // SubMenu dan Master Data
        MenuItem masterEmployee = new MenuItem(null, true, null, null, null, "Employee", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main_content_panel.removeAll();
                main_content_panel.add(new Employee(), BorderLayout.CENTER);
                main_content_panel.repaint();
                main_content_panel.revalidate();
            }
        });
        MenuItem masterPosition = new MenuItem(null, true, null, null, null, "Position", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main_content_panel.removeAll();
                main_content_panel.add(new Level(), BorderLayout.CENTER);
                main_content_panel.repaint();
                main_content_panel.revalidate();
            }
        });
        MenuItem masterDepartement = new MenuItem(null, true, null, null, null, "Departement", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main_content_panel.removeAll();
//                main_content_panel.add(new FormClasses(), BorderLayout.CENTER);
                main_content_panel.repaint();
                main_content_panel.revalidate();
            }
        });
        MenuItem masterSalary = new MenuItem(null, true, null, null, null, "Salary", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main_content_panel.removeAll();
//                main_content_panel.add(new FormClasses(), BorderLayout.CENTER);
                main_content_panel.repaint();
                main_content_panel.revalidate();
            }
        });
        MenuItem masterAttendanceLimit = new MenuItem(null, true, null, null, null, "Attendance Limit", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main_content_panel.removeAll();
//                main_content_panel.add(new FormClasses(), BorderLayout.CENTER);
                main_content_panel.repaint();
                main_content_panel.revalidate();
            }
        });
        MenuItem menuMaster = new MenuItem(masterIcon, false, null, rightArrow, downArrow, "Master Data", null, masterEmployee, masterPosition, masterDepartement, masterSalary, masterAttendanceLimit);

//        MenuItem menuClassSchedule = new MenuItem(scheduleIcon, false, null, "Jadwal Kelas", new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                main_content_panel.removeAll();
//                main_content_panel.add(new FormClassSchedule(), BorderLayout.CENTER);
//                main_content_panel.repaint();
//                main_content_panel.revalidate();
//            }
//        });

//        MenuItem menuClassRegist = new MenuItem(registIcon, false, null, "Daftar Kelas", new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                main_content_panel.removeAll();
//                main_content_panel.add(new FormClassRegist(), BorderLayout.CENTER);
//                main_content_panel.repaint();
//                main_content_panel.revalidate();
//            }
//        });

        // SubMenu dan Master Report
//        MenuItem menuReport = new MenuItem(reportIcon, false, null, "Laporan", new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                main_content_panel.removeAll();
//                main_content_panel.add(new ReportForm(), BorderLayout.CENTER);
//                main_content_panel.repaint();
//                main_content_panel.revalidate();
//            }
//        });

        // SubMenu dan Master Report
//        MenuItem menuLogout = new MenuItem(logoutIcon, false, null, "Keluar", new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                dispose();
//
//                Login formLogin = new Login();
//                formLogin.setVisible(true);
//            }
//        });

        // MenuItem masterAttendance = new MenuItem(null, true, subIcon, "Absensi", null);
        // MenuItem menuReport = new MenuItem(reportIcon, false, null, "Report", null, masterAttendance);
//        addMenu(menuDashboard, menuMaster);
        try {
            String sql = "SELECT idlevelemployee FROM employee WHERE isdeleted = 0 AND nik = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, nik);

            ResultSet hasil = stmt.executeQuery();
            if (hasil.next()) {
                int levelId = hasil.getInt("idlevelemployee");
                if (levelId == 6) {
                    addMenu(menuDashboard);
                } else {
                    addMenu(menuDashboard, menuMaster);
                }

            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }

    private void addMenu(MenuItem... menu) {
        for (MenuItem menu1 : menu) {
            menu_panel.add(menu1);
            ArrayList<MenuItem> subMenu = menu1.getSubMenu();
            for (MenuItem m : subMenu) {
                addMenu(m);
            }
        }
        menu_panel.revalidate();
    }
}
